/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteImport } from './routes/dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept'
import { Route as InternalDomainCheckRouteImport } from './routes/internal/domain-check'
import { Route as DashSubdomainsRouteImport } from './routes/dash/subdomains'
import { Route as DashSettingsRouteImport } from './routes/dash/settings'
import { Route as DashRequestsRouteImport } from './routes/dash/requests'
import { Route as DashMembersRouteImport } from './routes/dash/members'
import { Route as DashInstallRouteImport } from './routes/dash/install'
import { Route as DashDomainsRouteImport } from './routes/dash/domains'
import { Route as DashBillingRouteImport } from './routes/dash/billing'
import { Route as DashActivityRouteImport } from './routes/dash/activity'
import { Route as CliLoginRouteImport } from './routes/cli.login'
import { Route as ApiSubdomainsRouteImport } from './routes/api/subdomains'
import { Route as ApiRequestsRouteImport } from './routes/api/requests'
import { Route as ApiAuthTokensRouteImport } from './routes/api/auth-tokens'
import { Route as DashTunnelsIndexRouteImport } from './routes/dash/tunnels/index'
import { Route as ApiTunnelsIndexRouteImport } from './routes/api/tunnels/index'
import { Route as ApiDomainsIndexRouteImport } from './routes/api/domains/index'
import { Route as DashTunnelsTunnelIdRouteImport } from './routes/dash/tunnels/$tunnelId'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiTunnelsTunnelIdRouteImport } from './routes/api/tunnels/$tunnelId'
import { Route as ApiTunnelRegisterRouteImport } from './routes/api/tunnel/register'
import { Route as ApiTunnelCheckSubdomainRouteImport } from './routes/api/tunnel/check-subdomain'
import { Route as ApiTunnelAuthRouteImport } from './routes/api/tunnel/auth'
import { Route as ApiSubscriptionsOrganizationIdRouteImport } from './routes/api/subscriptions/$organizationId'
import { Route as ApiSubdomainsSubdomainIdRouteImport } from './routes/api/subdomains/$subdomainId'
import { Route as ApiStatsTunnelRouteImport } from './routes/api/stats/tunnel'
import { Route as ApiStatsOverviewRouteImport } from './routes/api/stats/overview'
import { Route as ApiStatsBandwidthRouteImport } from './routes/api/stats/bandwidth'
import { Route as ApiPortalPolarRouteImport } from './routes/api/portal/polar'
import { Route as ApiMeOrgsRouteImport } from './routes/api/me/orgs'
import { Route as ApiDomainsDomainIdRouteImport } from './routes/api/domains/$domainId'
import { Route as ApiDomainVerifyOwnershipRouteImport } from './routes/api/domain/verify-ownership'
import { Route as ApiCliLoginRouteImport } from './routes/api/cli/login'
import { Route as ApiCliExchangeRouteImport } from './routes/api/cli/exchange'
import { Route as ApiCliCompleteRouteImport } from './routes/api/cli/complete'
import { Route as ApiCheckoutPolarRouteImport } from './routes/api/checkout/polar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTunnelsTunnelIdStopRouteImport } from './routes/api/tunnels/$tunnelId.stop'
import { Route as ApiDomainsDomainIdVerifyRouteImport } from './routes/api/domains/$domainId.verify'
import { Route as ApiCliLoginStatusRouteImport } from './routes/api/cli/login/status'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalDomainCheckRoute = InternalDomainCheckRouteImport.update({
  id: '/internal/domain-check',
  path: '/internal/domain-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DashSubdomainsRoute = DashSubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashRequestsRoute = DashRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashRoute,
} as any)
const DashMembersRoute = DashMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashRoute,
} as any)
const DashInstallRoute = DashInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => DashRoute,
} as any)
const DashDomainsRoute = DashDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashRoute,
} as any)
const DashBillingRoute = DashBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashRoute,
} as any)
const DashActivityRoute = DashActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashRoute,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli/login',
  path: '/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubdomainsRoute = ApiSubdomainsRouteImport.update({
  id: '/api/subdomains',
  path: '/api/subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTokensRoute = ApiAuthTokensRouteImport.update({
  id: '/api/auth-tokens',
  path: '/api/auth-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const DashTunnelsIndexRoute = DashTunnelsIndexRouteImport.update({
  id: '/tunnels/',
  path: '/tunnels/',
  getParentRoute: () => DashRoute,
} as any)
const ApiTunnelsIndexRoute = ApiTunnelsIndexRouteImport.update({
  id: '/api/tunnels/',
  path: '/api/tunnels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainsIndexRoute = ApiDomainsIndexRouteImport.update({
  id: '/api/domains/',
  path: '/api/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashTunnelsTunnelIdRoute = DashTunnelsTunnelIdRouteImport.update({
  id: '/tunnels/$tunnelId',
  path: '/tunnels/$tunnelId',
  getParentRoute: () => DashRoute,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelsTunnelIdRoute = ApiTunnelsTunnelIdRouteImport.update({
  id: '/api/tunnels/$tunnelId',
  path: '/api/tunnels/$tunnelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelRegisterRoute = ApiTunnelRegisterRouteImport.update({
  id: '/api/tunnel/register',
  path: '/api/tunnel/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelCheckSubdomainRoute = ApiTunnelCheckSubdomainRouteImport.update({
  id: '/api/tunnel/check-subdomain',
  path: '/api/tunnel/check-subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelAuthRoute = ApiTunnelAuthRouteImport.update({
  id: '/api/tunnel/auth',
  path: '/api/tunnel/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsOrganizationIdRoute =
  ApiSubscriptionsOrganizationIdRouteImport.update({
    id: '/api/subscriptions/$organizationId',
    path: '/api/subscriptions/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSubdomainsSubdomainIdRoute =
  ApiSubdomainsSubdomainIdRouteImport.update({
    id: '/$subdomainId',
    path: '/$subdomainId',
    getParentRoute: () => ApiSubdomainsRoute,
  } as any)
const ApiStatsTunnelRoute = ApiStatsTunnelRouteImport.update({
  id: '/api/stats/tunnel',
  path: '/api/stats/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsOverviewRoute = ApiStatsOverviewRouteImport.update({
  id: '/api/stats/overview',
  path: '/api/stats/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsBandwidthRoute = ApiStatsBandwidthRouteImport.update({
  id: '/api/stats/bandwidth',
  path: '/api/stats/bandwidth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalPolarRoute = ApiPortalPolarRouteImport.update({
  id: '/api/portal/polar',
  path: '/api/portal/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeOrgsRoute = ApiMeOrgsRouteImport.update({
  id: '/api/me/orgs',
  path: '/api/me/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainsDomainIdRoute = ApiDomainsDomainIdRouteImport.update({
  id: '/api/domains/$domainId',
  path: '/api/domains/$domainId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainVerifyOwnershipRoute =
  ApiDomainVerifyOwnershipRouteImport.update({
    id: '/api/domain/verify-ownership',
    path: '/api/domain/verify-ownership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliLoginRoute = ApiCliLoginRouteImport.update({
  id: '/api/cli/login',
  path: '/api/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliExchangeRoute = ApiCliExchangeRouteImport.update({
  id: '/api/cli/exchange',
  path: '/api/cli/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliCompleteRoute = ApiCliCompleteRouteImport.update({
  id: '/api/cli/complete',
  path: '/api/cli/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutPolarRoute = ApiCheckoutPolarRouteImport.update({
  id: '/api/checkout/polar',
  path: '/api/checkout/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelsTunnelIdStopRoute = ApiTunnelsTunnelIdStopRouteImport.update({
  id: '/stop',
  path: '/stop',
  getParentRoute: () => ApiTunnelsTunnelIdRoute,
} as any)
const ApiDomainsDomainIdVerifyRoute =
  ApiDomainsDomainIdVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => ApiDomainsDomainIdRoute,
  } as any)
const ApiCliLoginStatusRoute = ApiCliLoginStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiCliLoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/auth-tokens': typeof ApiAuthTokensRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/subdomains': typeof ApiSubdomainsRouteWithChildren
  '/cli/login': typeof CliLoginRoute
  '/dash/activity': typeof DashActivityRoute
  '/dash/billing': typeof DashBillingRoute
  '/dash/domains': typeof DashDomainsRoute
  '/dash/install': typeof DashInstallRoute
  '/dash/members': typeof DashMembersRoute
  '/dash/requests': typeof DashRequestsRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash/subdomains': typeof DashSubdomainsRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/dash/': typeof DashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/domains/$domainId': typeof ApiDomainsDomainIdRouteWithChildren
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/portal/polar': typeof ApiPortalPolarRoute
  '/api/stats/bandwidth': typeof ApiStatsBandwidthRoute
  '/api/stats/overview': typeof ApiStatsOverviewRoute
  '/api/stats/tunnel': typeof ApiStatsTunnelRoute
  '/api/subdomains/$subdomainId': typeof ApiSubdomainsSubdomainIdRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/tunnels/$tunnelId': typeof ApiTunnelsTunnelIdRouteWithChildren
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/api/domains': typeof ApiDomainsIndexRoute
  '/api/tunnels': typeof ApiTunnelsIndexRoute
  '/dash/tunnels': typeof DashTunnelsIndexRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/domains/$domainId/verify': typeof ApiDomainsDomainIdVerifyRoute
  '/api/tunnels/$tunnelId/stop': typeof ApiTunnelsTunnelIdStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/auth-tokens': typeof ApiAuthTokensRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/subdomains': typeof ApiSubdomainsRouteWithChildren
  '/cli/login': typeof CliLoginRoute
  '/dash/activity': typeof DashActivityRoute
  '/dash/billing': typeof DashBillingRoute
  '/dash/domains': typeof DashDomainsRoute
  '/dash/install': typeof DashInstallRoute
  '/dash/members': typeof DashMembersRoute
  '/dash/requests': typeof DashRequestsRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash/subdomains': typeof DashSubdomainsRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/dash': typeof DashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/domains/$domainId': typeof ApiDomainsDomainIdRouteWithChildren
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/portal/polar': typeof ApiPortalPolarRoute
  '/api/stats/bandwidth': typeof ApiStatsBandwidthRoute
  '/api/stats/overview': typeof ApiStatsOverviewRoute
  '/api/stats/tunnel': typeof ApiStatsTunnelRoute
  '/api/subdomains/$subdomainId': typeof ApiSubdomainsSubdomainIdRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/tunnels/$tunnelId': typeof ApiTunnelsTunnelIdRouteWithChildren
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/api/domains': typeof ApiDomainsIndexRoute
  '/api/tunnels': typeof ApiTunnelsIndexRoute
  '/dash/tunnels': typeof DashTunnelsIndexRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/domains/$domainId/verify': typeof ApiDomainsDomainIdVerifyRoute
  '/api/tunnels/$tunnelId/stop': typeof ApiTunnelsTunnelIdStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/auth-tokens': typeof ApiAuthTokensRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/subdomains': typeof ApiSubdomainsRouteWithChildren
  '/cli/login': typeof CliLoginRoute
  '/dash/activity': typeof DashActivityRoute
  '/dash/billing': typeof DashBillingRoute
  '/dash/domains': typeof DashDomainsRoute
  '/dash/install': typeof DashInstallRoute
  '/dash/members': typeof DashMembersRoute
  '/dash/requests': typeof DashRequestsRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash/subdomains': typeof DashSubdomainsRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/dash/': typeof DashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/domains/$domainId': typeof ApiDomainsDomainIdRouteWithChildren
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/portal/polar': typeof ApiPortalPolarRoute
  '/api/stats/bandwidth': typeof ApiStatsBandwidthRoute
  '/api/stats/overview': typeof ApiStatsOverviewRoute
  '/api/stats/tunnel': typeof ApiStatsTunnelRoute
  '/api/subdomains/$subdomainId': typeof ApiSubdomainsSubdomainIdRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/tunnels/$tunnelId': typeof ApiTunnelsTunnelIdRouteWithChildren
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/dash/tunnels/$tunnelId': typeof DashTunnelsTunnelIdRoute
  '/api/domains/': typeof ApiDomainsIndexRoute
  '/api/tunnels/': typeof ApiTunnelsIndexRoute
  '/dash/tunnels/': typeof DashTunnelsIndexRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/domains/$domainId/verify': typeof ApiDomainsDomainIdVerifyRoute
  '/api/tunnels/$tunnelId/stop': typeof ApiTunnelsTunnelIdStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash'
    | '/login'
    | '/onboarding'
    | '/api/auth-tokens'
    | '/api/requests'
    | '/api/subdomains'
    | '/cli/login'
    | '/dash/activity'
    | '/dash/billing'
    | '/dash/domains'
    | '/dash/install'
    | '/dash/members'
    | '/dash/requests'
    | '/dash/settings'
    | '/dash/subdomains'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/dash/'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/domains/$domainId'
    | '/api/me/orgs'
    | '/api/portal/polar'
    | '/api/stats/bandwidth'
    | '/api/stats/overview'
    | '/api/stats/tunnel'
    | '/api/subdomains/$subdomainId'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/tunnels/$tunnelId'
    | '/api/webhooks/polar'
    | '/dash/tunnels/$tunnelId'
    | '/api/domains'
    | '/api/tunnels'
    | '/dash/tunnels'
    | '/api/cli/login/status'
    | '/api/domains/$domainId/verify'
    | '/api/tunnels/$tunnelId/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/api/auth-tokens'
    | '/api/requests'
    | '/api/subdomains'
    | '/cli/login'
    | '/dash/activity'
    | '/dash/billing'
    | '/dash/domains'
    | '/dash/install'
    | '/dash/members'
    | '/dash/requests'
    | '/dash/settings'
    | '/dash/subdomains'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/dash'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/domains/$domainId'
    | '/api/me/orgs'
    | '/api/portal/polar'
    | '/api/stats/bandwidth'
    | '/api/stats/overview'
    | '/api/stats/tunnel'
    | '/api/subdomains/$subdomainId'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/tunnels/$tunnelId'
    | '/api/webhooks/polar'
    | '/dash/tunnels/$tunnelId'
    | '/api/domains'
    | '/api/tunnels'
    | '/dash/tunnels'
    | '/api/cli/login/status'
    | '/api/domains/$domainId/verify'
    | '/api/tunnels/$tunnelId/stop'
  id:
    | '__root__'
    | '/'
    | '/dash'
    | '/login'
    | '/onboarding'
    | '/api/auth-tokens'
    | '/api/requests'
    | '/api/subdomains'
    | '/cli/login'
    | '/dash/activity'
    | '/dash/billing'
    | '/dash/domains'
    | '/dash/install'
    | '/dash/members'
    | '/dash/requests'
    | '/dash/settings'
    | '/dash/subdomains'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/dash/'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/domains/$domainId'
    | '/api/me/orgs'
    | '/api/portal/polar'
    | '/api/stats/bandwidth'
    | '/api/stats/overview'
    | '/api/stats/tunnel'
    | '/api/subdomains/$subdomainId'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/tunnels/$tunnelId'
    | '/api/webhooks/polar'
    | '/dash/tunnels/$tunnelId'
    | '/api/domains/'
    | '/api/tunnels/'
    | '/dash/tunnels/'
    | '/api/cli/login/status'
    | '/api/domains/$domainId/verify'
    | '/api/tunnels/$tunnelId/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthTokensRoute: typeof ApiAuthTokensRoute
  ApiRequestsRoute: typeof ApiRequestsRoute
  ApiSubdomainsRoute: typeof ApiSubdomainsRouteWithChildren
  CliLoginRoute: typeof CliLoginRoute
  InternalDomainCheckRoute: typeof InternalDomainCheckRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckoutPolarRoute: typeof ApiCheckoutPolarRoute
  ApiCliCompleteRoute: typeof ApiCliCompleteRoute
  ApiCliExchangeRoute: typeof ApiCliExchangeRoute
  ApiCliLoginRoute: typeof ApiCliLoginRouteWithChildren
  ApiDomainVerifyOwnershipRoute: typeof ApiDomainVerifyOwnershipRoute
  ApiDomainsDomainIdRoute: typeof ApiDomainsDomainIdRouteWithChildren
  ApiMeOrgsRoute: typeof ApiMeOrgsRoute
  ApiPortalPolarRoute: typeof ApiPortalPolarRoute
  ApiStatsBandwidthRoute: typeof ApiStatsBandwidthRoute
  ApiStatsOverviewRoute: typeof ApiStatsOverviewRoute
  ApiStatsTunnelRoute: typeof ApiStatsTunnelRoute
  ApiSubscriptionsOrganizationIdRoute: typeof ApiSubscriptionsOrganizationIdRoute
  ApiTunnelAuthRoute: typeof ApiTunnelAuthRoute
  ApiTunnelCheckSubdomainRoute: typeof ApiTunnelCheckSubdomainRoute
  ApiTunnelRegisterRoute: typeof ApiTunnelRegisterRoute
  ApiTunnelsTunnelIdRoute: typeof ApiTunnelsTunnelIdRouteWithChildren
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
  ApiDomainsIndexRoute: typeof ApiDomainsIndexRoute
  ApiTunnelsIndexRoute: typeof ApiTunnelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/domain-check': {
      id: '/internal/domain-check'
      path: '/internal/domain-check'
      fullPath: '/internal/domain-check'
      preLoaderRoute: typeof InternalDomainCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/subdomains': {
      id: '/dash/subdomains'
      path: '/subdomains'
      fullPath: '/dash/subdomains'
      preLoaderRoute: typeof DashSubdomainsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/settings': {
      id: '/dash/settings'
      path: '/settings'
      fullPath: '/dash/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/requests': {
      id: '/dash/requests'
      path: '/requests'
      fullPath: '/dash/requests'
      preLoaderRoute: typeof DashRequestsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/members': {
      id: '/dash/members'
      path: '/members'
      fullPath: '/dash/members'
      preLoaderRoute: typeof DashMembersRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/install': {
      id: '/dash/install'
      path: '/install'
      fullPath: '/dash/install'
      preLoaderRoute: typeof DashInstallRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/domains': {
      id: '/dash/domains'
      path: '/domains'
      fullPath: '/dash/domains'
      preLoaderRoute: typeof DashDomainsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/billing': {
      id: '/dash/billing'
      path: '/billing'
      fullPath: '/dash/billing'
      preLoaderRoute: typeof DashBillingRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/activity': {
      id: '/dash/activity'
      path: '/activity'
      fullPath: '/dash/activity'
      preLoaderRoute: typeof DashActivityRouteImport
      parentRoute: typeof DashRoute
    }
    '/cli/login': {
      id: '/cli/login'
      path: '/cli/login'
      fullPath: '/cli/login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subdomains': {
      id: '/api/subdomains'
      path: '/api/subdomains'
      fullPath: '/api/subdomains'
      preLoaderRoute: typeof ApiSubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-tokens': {
      id: '/api/auth-tokens'
      path: '/api/auth-tokens'
      fullPath: '/api/auth-tokens'
      preLoaderRoute: typeof ApiAuthTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/tunnels/': {
      id: '/dash/tunnels/'
      path: '/tunnels'
      fullPath: '/dash/tunnels'
      preLoaderRoute: typeof DashTunnelsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/tunnels/': {
      id: '/api/tunnels/'
      path: '/api/tunnels'
      fullPath: '/api/tunnels'
      preLoaderRoute: typeof ApiTunnelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domains/': {
      id: '/api/domains/'
      path: '/api/domains'
      fullPath: '/api/domains'
      preLoaderRoute: typeof ApiDomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/tunnels/$tunnelId': {
      id: '/dash/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/dash/tunnels/$tunnelId'
      preLoaderRoute: typeof DashTunnelsTunnelIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnels/$tunnelId': {
      id: '/api/tunnels/$tunnelId'
      path: '/api/tunnels/$tunnelId'
      fullPath: '/api/tunnels/$tunnelId'
      preLoaderRoute: typeof ApiTunnelsTunnelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/register': {
      id: '/api/tunnel/register'
      path: '/api/tunnel/register'
      fullPath: '/api/tunnel/register'
      preLoaderRoute: typeof ApiTunnelRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/check-subdomain': {
      id: '/api/tunnel/check-subdomain'
      path: '/api/tunnel/check-subdomain'
      fullPath: '/api/tunnel/check-subdomain'
      preLoaderRoute: typeof ApiTunnelCheckSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/auth': {
      id: '/api/tunnel/auth'
      path: '/api/tunnel/auth'
      fullPath: '/api/tunnel/auth'
      preLoaderRoute: typeof ApiTunnelAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/$organizationId': {
      id: '/api/subscriptions/$organizationId'
      path: '/api/subscriptions/$organizationId'
      fullPath: '/api/subscriptions/$organizationId'
      preLoaderRoute: typeof ApiSubscriptionsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subdomains/$subdomainId': {
      id: '/api/subdomains/$subdomainId'
      path: '/$subdomainId'
      fullPath: '/api/subdomains/$subdomainId'
      preLoaderRoute: typeof ApiSubdomainsSubdomainIdRouteImport
      parentRoute: typeof ApiSubdomainsRoute
    }
    '/api/stats/tunnel': {
      id: '/api/stats/tunnel'
      path: '/api/stats/tunnel'
      fullPath: '/api/stats/tunnel'
      preLoaderRoute: typeof ApiStatsTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/overview': {
      id: '/api/stats/overview'
      path: '/api/stats/overview'
      fullPath: '/api/stats/overview'
      preLoaderRoute: typeof ApiStatsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/bandwidth': {
      id: '/api/stats/bandwidth'
      path: '/api/stats/bandwidth'
      fullPath: '/api/stats/bandwidth'
      preLoaderRoute: typeof ApiStatsBandwidthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/polar': {
      id: '/api/portal/polar'
      path: '/api/portal/polar'
      fullPath: '/api/portal/polar'
      preLoaderRoute: typeof ApiPortalPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/orgs': {
      id: '/api/me/orgs'
      path: '/api/me/orgs'
      fullPath: '/api/me/orgs'
      preLoaderRoute: typeof ApiMeOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domains/$domainId': {
      id: '/api/domains/$domainId'
      path: '/api/domains/$domainId'
      fullPath: '/api/domains/$domainId'
      preLoaderRoute: typeof ApiDomainsDomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domain/verify-ownership': {
      id: '/api/domain/verify-ownership'
      path: '/api/domain/verify-ownership'
      fullPath: '/api/domain/verify-ownership'
      preLoaderRoute: typeof ApiDomainVerifyOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/login': {
      id: '/api/cli/login'
      path: '/api/cli/login'
      fullPath: '/api/cli/login'
      preLoaderRoute: typeof ApiCliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/exchange': {
      id: '/api/cli/exchange'
      path: '/api/cli/exchange'
      fullPath: '/api/cli/exchange'
      preLoaderRoute: typeof ApiCliExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/complete': {
      id: '/api/cli/complete'
      path: '/api/cli/complete'
      fullPath: '/api/cli/complete'
      preLoaderRoute: typeof ApiCliCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/polar': {
      id: '/api/checkout/polar'
      path: '/api/checkout/polar'
      fullPath: '/api/checkout/polar'
      preLoaderRoute: typeof ApiCheckoutPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnels/$tunnelId/stop': {
      id: '/api/tunnels/$tunnelId/stop'
      path: '/stop'
      fullPath: '/api/tunnels/$tunnelId/stop'
      preLoaderRoute: typeof ApiTunnelsTunnelIdStopRouteImport
      parentRoute: typeof ApiTunnelsTunnelIdRoute
    }
    '/api/domains/$domainId/verify': {
      id: '/api/domains/$domainId/verify'
      path: '/verify'
      fullPath: '/api/domains/$domainId/verify'
      preLoaderRoute: typeof ApiDomainsDomainIdVerifyRouteImport
      parentRoute: typeof ApiDomainsDomainIdRoute
    }
    '/api/cli/login/status': {
      id: '/api/cli/login/status'
      path: '/status'
      fullPath: '/api/cli/login/status'
      preLoaderRoute: typeof ApiCliLoginStatusRouteImport
      parentRoute: typeof ApiCliLoginRoute
    }
  }
}

interface DashRouteChildren {
  DashActivityRoute: typeof DashActivityRoute
  DashBillingRoute: typeof DashBillingRoute
  DashDomainsRoute: typeof DashDomainsRoute
  DashInstallRoute: typeof DashInstallRoute
  DashMembersRoute: typeof DashMembersRoute
  DashRequestsRoute: typeof DashRequestsRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashSubdomainsRoute: typeof DashSubdomainsRoute
  DashIndexRoute: typeof DashIndexRoute
  DashTunnelsTunnelIdRoute: typeof DashTunnelsTunnelIdRoute
  DashTunnelsIndexRoute: typeof DashTunnelsIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashActivityRoute: DashActivityRoute,
  DashBillingRoute: DashBillingRoute,
  DashDomainsRoute: DashDomainsRoute,
  DashInstallRoute: DashInstallRoute,
  DashMembersRoute: DashMembersRoute,
  DashRequestsRoute: DashRequestsRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashSubdomainsRoute: DashSubdomainsRoute,
  DashIndexRoute: DashIndexRoute,
  DashTunnelsTunnelIdRoute: DashTunnelsTunnelIdRoute,
  DashTunnelsIndexRoute: DashTunnelsIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

interface ApiSubdomainsRouteChildren {
  ApiSubdomainsSubdomainIdRoute: typeof ApiSubdomainsSubdomainIdRoute
}

const ApiSubdomainsRouteChildren: ApiSubdomainsRouteChildren = {
  ApiSubdomainsSubdomainIdRoute: ApiSubdomainsSubdomainIdRoute,
}

const ApiSubdomainsRouteWithChildren = ApiSubdomainsRoute._addFileChildren(
  ApiSubdomainsRouteChildren,
)

interface ApiCliLoginRouteChildren {
  ApiCliLoginStatusRoute: typeof ApiCliLoginStatusRoute
}

const ApiCliLoginRouteChildren: ApiCliLoginRouteChildren = {
  ApiCliLoginStatusRoute: ApiCliLoginStatusRoute,
}

const ApiCliLoginRouteWithChildren = ApiCliLoginRoute._addFileChildren(
  ApiCliLoginRouteChildren,
)

interface ApiDomainsDomainIdRouteChildren {
  ApiDomainsDomainIdVerifyRoute: typeof ApiDomainsDomainIdVerifyRoute
}

const ApiDomainsDomainIdRouteChildren: ApiDomainsDomainIdRouteChildren = {
  ApiDomainsDomainIdVerifyRoute: ApiDomainsDomainIdVerifyRoute,
}

const ApiDomainsDomainIdRouteWithChildren =
  ApiDomainsDomainIdRoute._addFileChildren(ApiDomainsDomainIdRouteChildren)

interface ApiTunnelsTunnelIdRouteChildren {
  ApiTunnelsTunnelIdStopRoute: typeof ApiTunnelsTunnelIdStopRoute
}

const ApiTunnelsTunnelIdRouteChildren: ApiTunnelsTunnelIdRouteChildren = {
  ApiTunnelsTunnelIdStopRoute: ApiTunnelsTunnelIdStopRoute,
}

const ApiTunnelsTunnelIdRouteWithChildren =
  ApiTunnelsTunnelIdRoute._addFileChildren(ApiTunnelsTunnelIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthTokensRoute: ApiAuthTokensRoute,
  ApiRequestsRoute: ApiRequestsRoute,
  ApiSubdomainsRoute: ApiSubdomainsRouteWithChildren,
  CliLoginRoute: CliLoginRoute,
  InternalDomainCheckRoute: InternalDomainCheckRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckoutPolarRoute: ApiCheckoutPolarRoute,
  ApiCliCompleteRoute: ApiCliCompleteRoute,
  ApiCliExchangeRoute: ApiCliExchangeRoute,
  ApiCliLoginRoute: ApiCliLoginRouteWithChildren,
  ApiDomainVerifyOwnershipRoute: ApiDomainVerifyOwnershipRoute,
  ApiDomainsDomainIdRoute: ApiDomainsDomainIdRouteWithChildren,
  ApiMeOrgsRoute: ApiMeOrgsRoute,
  ApiPortalPolarRoute: ApiPortalPolarRoute,
  ApiStatsBandwidthRoute: ApiStatsBandwidthRoute,
  ApiStatsOverviewRoute: ApiStatsOverviewRoute,
  ApiStatsTunnelRoute: ApiStatsTunnelRoute,
  ApiSubscriptionsOrganizationIdRoute: ApiSubscriptionsOrganizationIdRoute,
  ApiTunnelAuthRoute: ApiTunnelAuthRoute,
  ApiTunnelCheckSubdomainRoute: ApiTunnelCheckSubdomainRoute,
  ApiTunnelRegisterRoute: ApiTunnelRegisterRoute,
  ApiTunnelsTunnelIdRoute: ApiTunnelsTunnelIdRouteWithChildren,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
  ApiDomainsIndexRoute: ApiDomainsIndexRoute,
  ApiTunnelsIndexRoute: ApiTunnelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
