/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViteRouteImport } from './routes/vite'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectRouteImport } from './routes/select'
import { Route as ReportBugRouteImport } from './routes/report-bug'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NextjsRouteImport } from './routes/nextjs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept'
import { Route as InternalDomainCheckRouteImport } from './routes/internal/domain-check'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as CliLoginRouteImport } from './routes/cli.login'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminTunnelsRouteImport } from './routes/admin/tunnels'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminChartsRouteImport } from './routes/admin/charts'
import { Route as AdminActionsRouteImport } from './routes/admin/actions'
import { Route as OrgSlugTokensRouteImport } from './routes/$orgSlug/tokens'
import { Route as OrgSlugSubdomainsRouteImport } from './routes/$orgSlug/subdomains'
import { Route as OrgSlugSettingsRouteImport } from './routes/$orgSlug/settings'
import { Route as OrgSlugRequestsRouteImport } from './routes/$orgSlug/requests'
import { Route as OrgSlugMembersRouteImport } from './routes/$orgSlug/members'
import { Route as OrgSlugInstallRouteImport } from './routes/$orgSlug/install'
import { Route as OrgSlugDomainsRouteImport } from './routes/$orgSlug/domains'
import { Route as OrgSlugBillingRouteImport } from './routes/$orgSlug/billing'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users.index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations.index'
import { Route as OrgSlugTunnelsIndexRouteImport } from './routes/$orgSlug/tunnels/index'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api/webhooks/paystack'
import { Route as ApiTunnelRegisterRouteImport } from './routes/api/tunnel/register'
import { Route as ApiTunnelCheckSubdomainRouteImport } from './routes/api/tunnel/check-subdomain'
import { Route as ApiTunnelAuthRouteImport } from './routes/api/tunnel/auth'
import { Route as ApiOrganizationsCheckSlugRouteImport } from './routes/api/organizations/check-slug'
import { Route as ApiMeOrgsRouteImport } from './routes/api/me/orgs'
import { Route as ApiDomainVerifyOwnershipRouteImport } from './routes/api/domain/verify-ownership'
import { Route as ApiDashboardWsTokenRouteImport } from './routes/api/dashboard/ws-token'
import { Route as ApiDashboardValidateWsTokenRouteImport } from './routes/api/dashboard/validate-ws-token'
import { Route as ApiCliLoginRouteImport } from './routes/api/cli/login'
import { Route as ApiCliExchangeRouteImport } from './routes/api/cli/exchange'
import { Route as ApiCliCompleteRouteImport } from './routes/api/cli/complete'
import { Route as ApiCheckoutPolarRouteImport } from './routes/api/checkout/polar'
import { Route as ApiCheckoutPaystackVerifyRouteImport } from './routes/api/checkout/paystack-verify'
import { Route as ApiCheckoutPaystackRouteImport } from './routes/api/checkout/paystack'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminTunnelsRouteImport } from './routes/api/admin/tunnels'
import { Route as ApiAdminSubscriptionsRouteImport } from './routes/api/admin/subscriptions'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAdminOrganizationsRouteImport } from './routes/api/admin/organizations'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminChartsRouteImport } from './routes/api/admin/charts'
import { Route as ApiOrgSlugSubscriptionsRouteImport } from './routes/api/$orgSlug/subscriptions'
import { Route as ApiOrgSlugSettingsRouteImport } from './routes/api/$orgSlug/settings'
import { Route as ApiOrgSlugRequestsRouteImport } from './routes/api/$orgSlug/requests'
import { Route as ApiOrgSlugAuthTokensRouteImport } from './routes/api/$orgSlug/auth-tokens'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as AdminOrganizationsSlugRouteImport } from './routes/admin/organizations.$slug'
import { Route as OrgSlugTunnelsTunnelIdRouteImport } from './routes/$orgSlug/tunnels/$tunnelId'
import { Route as OrgSlugSettingsProfileRouteImport } from './routes/$orgSlug/settings/profile'
import { Route as OrgSlugSettingsOrganizationRouteImport } from './routes/$orgSlug/settings/organization'
import { Route as ApiOrgSlugTunnelsIndexRouteImport } from './routes/api/$orgSlug/tunnels/index'
import { Route as ApiOrgSlugSubdomainsIndexRouteImport } from './routes/api/$orgSlug/subdomains/index'
import { Route as ApiOrgSlugDomainsIndexRouteImport } from './routes/api/$orgSlug/domains/index'
import { Route as ApiSubscriptionsOrgSlugCancelRouteImport } from './routes/api/subscriptions/$orgSlug/cancel'
import { Route as ApiCliLoginStatusRouteImport } from './routes/api/cli/login/status'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api/admin/users.$userId'
import { Route as ApiAdminOrganizationsSlugRouteImport } from './routes/api/admin/organizations.$slug'
import { Route as ApiOrgSlugTunnelsTunnelIdRouteImport } from './routes/api/$orgSlug/tunnels/$tunnelId'
import { Route as ApiOrgSlugSubdomainsSubdomainIdRouteImport } from './routes/api/$orgSlug/subdomains/$subdomainId'
import { Route as ApiOrgSlugStatsTunnelRouteImport } from './routes/api/$orgSlug/stats/tunnel'
import { Route as ApiOrgSlugStatsProtocolRouteImport } from './routes/api/$orgSlug/stats/protocol'
import { Route as ApiOrgSlugStatsOverviewRouteImport } from './routes/api/$orgSlug/stats/overview'
import { Route as ApiOrgSlugStatsBandwidthRouteImport } from './routes/api/$orgSlug/stats/bandwidth'
import { Route as ApiOrgSlugRequestsReplayRouteImport } from './routes/api/$orgSlug/requests/replay'
import { Route as ApiOrgSlugRequestsCaptureRouteImport } from './routes/api/$orgSlug/requests/capture'
import { Route as ApiOrgSlugPortalPolarRouteImport } from './routes/api/$orgSlug/portal/polar'
import { Route as ApiOrgSlugDomainsDomainIdRouteImport } from './routes/api/$orgSlug/domains/$domainId'
import { Route as ApiOrgSlugTunnelsTunnelIdStopRouteImport } from './routes/api/$orgSlug/tunnels/$tunnelId.stop'
import { Route as ApiOrgSlugDomainsDomainIdVerifyRouteImport } from './routes/api/$orgSlug/domains/$domainId.verify'

const ViteRoute = ViteRouteImport.update({
  id: '/vite',
  path: '/vite',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportBugRoute = ReportBugRouteImport.update({
  id: '/report-bug',
  path: '/report-bug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NextjsRoute = NextjsRouteImport.update({
  id: '/nextjs',
  path: '/nextjs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalDomainCheckRoute = InternalDomainCheckRouteImport.update({
  id: '/internal/domain-check',
  path: '/internal/domain-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli/login',
  path: '/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTunnelsRoute = AdminTunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChartsRoute = AdminChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActionsRoute = AdminActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AdminRoute,
} as any)
const OrgSlugTokensRoute = OrgSlugTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSubdomainsRoute = OrgSlugSubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsRoute = OrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugRequestsRoute = OrgSlugRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugMembersRoute = OrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugInstallRoute = OrgSlugInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugDomainsRoute = OrgSlugDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugBillingRoute = OrgSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgSlugRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRoute,
} as any)
const OrgSlugTunnelsIndexRoute = OrgSlugTunnelsIndexRouteImport.update({
  id: '/tunnels/',
  path: '/tunnels/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelRegisterRoute = ApiTunnelRegisterRouteImport.update({
  id: '/api/tunnel/register',
  path: '/api/tunnel/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelCheckSubdomainRoute = ApiTunnelCheckSubdomainRouteImport.update({
  id: '/api/tunnel/check-subdomain',
  path: '/api/tunnel/check-subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelAuthRoute = ApiTunnelAuthRouteImport.update({
  id: '/api/tunnel/auth',
  path: '/api/tunnel/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationsCheckSlugRoute =
  ApiOrganizationsCheckSlugRouteImport.update({
    id: '/api/organizations/check-slug',
    path: '/api/organizations/check-slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeOrgsRoute = ApiMeOrgsRouteImport.update({
  id: '/api/me/orgs',
  path: '/api/me/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainVerifyOwnershipRoute =
  ApiDomainVerifyOwnershipRouteImport.update({
    id: '/api/domain/verify-ownership',
    path: '/api/domain/verify-ownership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardWsTokenRoute = ApiDashboardWsTokenRouteImport.update({
  id: '/api/dashboard/ws-token',
  path: '/api/dashboard/ws-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardValidateWsTokenRoute =
  ApiDashboardValidateWsTokenRouteImport.update({
    id: '/api/dashboard/validate-ws-token',
    path: '/api/dashboard/validate-ws-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliLoginRoute = ApiCliLoginRouteImport.update({
  id: '/api/cli/login',
  path: '/api/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliExchangeRoute = ApiCliExchangeRouteImport.update({
  id: '/api/cli/exchange',
  path: '/api/cli/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliCompleteRoute = ApiCliCompleteRouteImport.update({
  id: '/api/cli/complete',
  path: '/api/cli/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutPolarRoute = ApiCheckoutPolarRouteImport.update({
  id: '/api/checkout/polar',
  path: '/api/checkout/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutPaystackVerifyRoute =
  ApiCheckoutPaystackVerifyRouteImport.update({
    id: '/api/checkout/paystack-verify',
    path: '/api/checkout/paystack-verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCheckoutPaystackRoute = ApiCheckoutPaystackRouteImport.update({
  id: '/api/checkout/paystack',
  path: '/api/checkout/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTunnelsRoute = ApiAdminTunnelsRouteImport.update({
  id: '/api/admin/tunnels',
  path: '/api/admin/tunnels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubscriptionsRoute = ApiAdminSubscriptionsRouteImport.update({
  id: '/api/admin/subscriptions',
  path: '/api/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrganizationsRoute = ApiAdminOrganizationsRouteImport.update({
  id: '/api/admin/organizations',
  path: '/api/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminChartsRoute = ApiAdminChartsRouteImport.update({
  id: '/api/admin/charts',
  path: '/api/admin/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSubscriptionsRoute = ApiOrgSlugSubscriptionsRouteImport.update({
  id: '/api/$orgSlug/subscriptions',
  path: '/api/$orgSlug/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSettingsRoute = ApiOrgSlugSettingsRouteImport.update({
  id: '/api/$orgSlug/settings',
  path: '/api/$orgSlug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugRequestsRoute = ApiOrgSlugRequestsRouteImport.update({
  id: '/api/$orgSlug/requests',
  path: '/api/$orgSlug/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugAuthTokensRoute = ApiOrgSlugAuthTokensRouteImport.update({
  id: '/api/$orgSlug/auth-tokens',
  path: '/api/$orgSlug/auth-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsSlugRoute = AdminOrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const OrgSlugTunnelsTunnelIdRoute = OrgSlugTunnelsTunnelIdRouteImport.update({
  id: '/tunnels/$tunnelId',
  path: '/tunnels/$tunnelId',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsProfileRoute = OrgSlugSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const OrgSlugSettingsOrganizationRoute =
  OrgSlugSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgSlugSettingsRoute,
  } as any)
const ApiOrgSlugTunnelsIndexRoute = ApiOrgSlugTunnelsIndexRouteImport.update({
  id: '/api/$orgSlug/tunnels/',
  path: '/api/$orgSlug/tunnels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSubdomainsIndexRoute =
  ApiOrgSlugSubdomainsIndexRouteImport.update({
    id: '/api/$orgSlug/subdomains/',
    path: '/api/$orgSlug/subdomains/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugDomainsIndexRoute = ApiOrgSlugDomainsIndexRouteImport.update({
  id: '/api/$orgSlug/domains/',
  path: '/api/$orgSlug/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsOrgSlugCancelRoute =
  ApiSubscriptionsOrgSlugCancelRouteImport.update({
    id: '/api/subscriptions/$orgSlug/cancel',
    path: '/api/subscriptions/$orgSlug/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliLoginStatusRoute = ApiCliLoginStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiCliLoginRoute,
} as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiAdminOrganizationsSlugRoute =
  ApiAdminOrganizationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ApiAdminOrganizationsRoute,
  } as any)
const ApiOrgSlugTunnelsTunnelIdRoute =
  ApiOrgSlugTunnelsTunnelIdRouteImport.update({
    id: '/api/$orgSlug/tunnels/$tunnelId',
    path: '/api/$orgSlug/tunnels/$tunnelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugSubdomainsSubdomainIdRoute =
  ApiOrgSlugSubdomainsSubdomainIdRouteImport.update({
    id: '/api/$orgSlug/subdomains/$subdomainId',
    path: '/api/$orgSlug/subdomains/$subdomainId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugStatsTunnelRoute = ApiOrgSlugStatsTunnelRouteImport.update({
  id: '/api/$orgSlug/stats/tunnel',
  path: '/api/$orgSlug/stats/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugStatsProtocolRoute = ApiOrgSlugStatsProtocolRouteImport.update({
  id: '/api/$orgSlug/stats/protocol',
  path: '/api/$orgSlug/stats/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugStatsOverviewRoute = ApiOrgSlugStatsOverviewRouteImport.update({
  id: '/api/$orgSlug/stats/overview',
  path: '/api/$orgSlug/stats/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugStatsBandwidthRoute =
  ApiOrgSlugStatsBandwidthRouteImport.update({
    id: '/api/$orgSlug/stats/bandwidth',
    path: '/api/$orgSlug/stats/bandwidth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugRequestsReplayRoute =
  ApiOrgSlugRequestsReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => ApiOrgSlugRequestsRoute,
  } as any)
const ApiOrgSlugRequestsCaptureRoute =
  ApiOrgSlugRequestsCaptureRouteImport.update({
    id: '/capture',
    path: '/capture',
    getParentRoute: () => ApiOrgSlugRequestsRoute,
  } as any)
const ApiOrgSlugPortalPolarRoute = ApiOrgSlugPortalPolarRouteImport.update({
  id: '/api/$orgSlug/portal/polar',
  path: '/api/$orgSlug/portal/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugDomainsDomainIdRoute =
  ApiOrgSlugDomainsDomainIdRouteImport.update({
    id: '/api/$orgSlug/domains/$domainId',
    path: '/api/$orgSlug/domains/$domainId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugTunnelsTunnelIdStopRoute =
  ApiOrgSlugTunnelsTunnelIdStopRouteImport.update({
    id: '/stop',
    path: '/stop',
    getParentRoute: () => ApiOrgSlugTunnelsTunnelIdRoute,
  } as any)
const ApiOrgSlugDomainsDomainIdVerifyRoute =
  ApiOrgSlugDomainsDomainIdVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => ApiOrgSlugDomainsDomainIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/nextjs': typeof NextjsRoute
  '/onboarding': typeof OnboardingRoute
  '/plugins': typeof PluginsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/report-bug': typeof ReportBugRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/vite': typeof ViteRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/subdomains': typeof OrgSlugSubdomainsRoute
  '/$orgSlug/tokens': typeof OrgSlugTokensRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tunnels': typeof AdminTunnelsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/admin/organizations/$slug': typeof AdminOrganizationsSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRouteWithChildren
  '/api/$orgSlug/settings': typeof ApiOrgSlugSettingsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/charts': typeof ApiAdminChartsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/organizations': typeof ApiAdminOrganizationsRouteWithChildren
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/admin/tunnels': typeof ApiAdminTunnelsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/paystack': typeof ApiCheckoutPaystackRoute
  '/api/checkout/paystack-verify': typeof ApiCheckoutPaystackVerifyRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/dashboard/validate-ws-token': typeof ApiDashboardValidateWsTokenRoute
  '/api/dashboard/ws-token': typeof ApiDashboardWsTokenRoute
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels': typeof OrgSlugTunnelsIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/$orgSlug/domains/$domainId': typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/requests/capture': typeof ApiOrgSlugRequestsCaptureRoute
  '/api/$orgSlug/requests/replay': typeof ApiOrgSlugRequestsReplayRoute
  '/api/$orgSlug/stats/bandwidth': typeof ApiOrgSlugStatsBandwidthRoute
  '/api/$orgSlug/stats/overview': typeof ApiOrgSlugStatsOverviewRoute
  '/api/$orgSlug/stats/protocol': typeof ApiOrgSlugStatsProtocolRoute
  '/api/$orgSlug/stats/tunnel': typeof ApiOrgSlugStatsTunnelRoute
  '/api/$orgSlug/subdomains/$subdomainId': typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  '/api/$orgSlug/tunnels/$tunnelId': typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  '/api/admin/organizations/$slug': typeof ApiAdminOrganizationsSlugRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/subscriptions/$orgSlug/cancel': typeof ApiSubscriptionsOrgSlugCancelRoute
  '/api/$orgSlug/domains': typeof ApiOrgSlugDomainsIndexRoute
  '/api/$orgSlug/subdomains': typeof ApiOrgSlugSubdomainsIndexRoute
  '/api/$orgSlug/tunnels': typeof ApiOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId/verify': typeof ApiOrgSlugDomainsDomainIdVerifyRoute
  '/api/$orgSlug/tunnels/$tunnelId/stop': typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/nextjs': typeof NextjsRoute
  '/onboarding': typeof OnboardingRoute
  '/plugins': typeof PluginsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/report-bug': typeof ReportBugRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/vite': typeof ViteRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/subdomains': typeof OrgSlugSubdomainsRoute
  '/$orgSlug/tokens': typeof OrgSlugTokensRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tunnels': typeof AdminTunnelsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/admin/organizations/$slug': typeof AdminOrganizationsSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRouteWithChildren
  '/api/$orgSlug/settings': typeof ApiOrgSlugSettingsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/charts': typeof ApiAdminChartsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/organizations': typeof ApiAdminOrganizationsRouteWithChildren
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/admin/tunnels': typeof ApiAdminTunnelsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/paystack': typeof ApiCheckoutPaystackRoute
  '/api/checkout/paystack-verify': typeof ApiCheckoutPaystackVerifyRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/dashboard/validate-ws-token': typeof ApiDashboardValidateWsTokenRoute
  '/api/dashboard/ws-token': typeof ApiDashboardWsTokenRoute
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels': typeof OrgSlugTunnelsIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/$orgSlug/domains/$domainId': typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/requests/capture': typeof ApiOrgSlugRequestsCaptureRoute
  '/api/$orgSlug/requests/replay': typeof ApiOrgSlugRequestsReplayRoute
  '/api/$orgSlug/stats/bandwidth': typeof ApiOrgSlugStatsBandwidthRoute
  '/api/$orgSlug/stats/overview': typeof ApiOrgSlugStatsOverviewRoute
  '/api/$orgSlug/stats/protocol': typeof ApiOrgSlugStatsProtocolRoute
  '/api/$orgSlug/stats/tunnel': typeof ApiOrgSlugStatsTunnelRoute
  '/api/$orgSlug/subdomains/$subdomainId': typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  '/api/$orgSlug/tunnels/$tunnelId': typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  '/api/admin/organizations/$slug': typeof ApiAdminOrganizationsSlugRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/subscriptions/$orgSlug/cancel': typeof ApiSubscriptionsOrgSlugCancelRoute
  '/api/$orgSlug/domains': typeof ApiOrgSlugDomainsIndexRoute
  '/api/$orgSlug/subdomains': typeof ApiOrgSlugSubdomainsIndexRoute
  '/api/$orgSlug/tunnels': typeof ApiOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId/verify': typeof ApiOrgSlugDomainsDomainIdVerifyRoute
  '/api/$orgSlug/tunnels/$tunnelId/stop': typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/nextjs': typeof NextjsRoute
  '/onboarding': typeof OnboardingRoute
  '/plugins': typeof PluginsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/report-bug': typeof ReportBugRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/vite': typeof ViteRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/subdomains': typeof OrgSlugSubdomainsRoute
  '/$orgSlug/tokens': typeof OrgSlugTokensRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tunnels': typeof AdminTunnelsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/admin/organizations/$slug': typeof AdminOrganizationsSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRouteWithChildren
  '/api/$orgSlug/settings': typeof ApiOrgSlugSettingsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/charts': typeof ApiAdminChartsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/organizations': typeof ApiAdminOrganizationsRouteWithChildren
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/admin/tunnels': typeof ApiAdminTunnelsRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/paystack': typeof ApiCheckoutPaystackRoute
  '/api/checkout/paystack-verify': typeof ApiCheckoutPaystackVerifyRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/dashboard/validate-ws-token': typeof ApiDashboardValidateWsTokenRoute
  '/api/dashboard/ws-token': typeof ApiDashboardWsTokenRoute
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels/': typeof OrgSlugTunnelsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/$orgSlug/domains/$domainId': typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/requests/capture': typeof ApiOrgSlugRequestsCaptureRoute
  '/api/$orgSlug/requests/replay': typeof ApiOrgSlugRequestsReplayRoute
  '/api/$orgSlug/stats/bandwidth': typeof ApiOrgSlugStatsBandwidthRoute
  '/api/$orgSlug/stats/overview': typeof ApiOrgSlugStatsOverviewRoute
  '/api/$orgSlug/stats/protocol': typeof ApiOrgSlugStatsProtocolRoute
  '/api/$orgSlug/stats/tunnel': typeof ApiOrgSlugStatsTunnelRoute
  '/api/$orgSlug/subdomains/$subdomainId': typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  '/api/$orgSlug/tunnels/$tunnelId': typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  '/api/admin/organizations/$slug': typeof ApiAdminOrganizationsSlugRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/subscriptions/$orgSlug/cancel': typeof ApiSubscriptionsOrgSlugCancelRoute
  '/api/$orgSlug/domains/': typeof ApiOrgSlugDomainsIndexRoute
  '/api/$orgSlug/subdomains/': typeof ApiOrgSlugSubdomainsIndexRoute
  '/api/$orgSlug/tunnels/': typeof ApiOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId/verify': typeof ApiOrgSlugDomainsDomainIdVerifyRoute
  '/api/$orgSlug/tunnels/$tunnelId/stop': typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/changelog'
    | '/contact'
    | '/email-templates'
    | '/login'
    | '/nextjs'
    | '/onboarding'
    | '/plugins'
    | '/pricing'
    | '/privacy'
    | '/report-bug'
    | '/select'
    | '/signup'
    | '/terms'
    | '/vite'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/settings'
    | '/$orgSlug/subdomains'
    | '/$orgSlug/tokens'
    | '/admin/actions'
    | '/admin/charts'
    | '/admin/subscriptions'
    | '/admin/tunnels'
    | '/api/health'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/admin/organizations/$slug'
    | '/admin/users/$userId'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/settings'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/charts'
    | '/api/admin/login'
    | '/api/admin/organizations'
    | '/api/admin/overview'
    | '/api/admin/stats'
    | '/api/admin/subscriptions'
    | '/api/admin/tunnels'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/checkout/paystack'
    | '/api/checkout/paystack-verify'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/dashboard/validate-ws-token'
    | '/api/dashboard/ws-token'
    | '/api/domain/verify-ownership'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/webhooks/paystack'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tunnels'
    | '/admin/organizations'
    | '/admin/users'
    | '/api/$orgSlug/domains/$domainId'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/requests/capture'
    | '/api/$orgSlug/requests/replay'
    | '/api/$orgSlug/stats/bandwidth'
    | '/api/$orgSlug/stats/overview'
    | '/api/$orgSlug/stats/protocol'
    | '/api/$orgSlug/stats/tunnel'
    | '/api/$orgSlug/subdomains/$subdomainId'
    | '/api/$orgSlug/tunnels/$tunnelId'
    | '/api/admin/organizations/$slug'
    | '/api/admin/users/$userId'
    | '/api/cli/login/status'
    | '/api/subscriptions/$orgSlug/cancel'
    | '/api/$orgSlug/domains'
    | '/api/$orgSlug/subdomains'
    | '/api/$orgSlug/tunnels'
    | '/api/$orgSlug/domains/$domainId/verify'
    | '/api/$orgSlug/tunnels/$tunnelId/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/changelog'
    | '/contact'
    | '/email-templates'
    | '/login'
    | '/nextjs'
    | '/onboarding'
    | '/plugins'
    | '/pricing'
    | '/privacy'
    | '/report-bug'
    | '/select'
    | '/signup'
    | '/terms'
    | '/vite'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/subdomains'
    | '/$orgSlug/tokens'
    | '/admin/actions'
    | '/admin/charts'
    | '/admin/subscriptions'
    | '/admin/tunnels'
    | '/api/health'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/admin/organizations/$slug'
    | '/admin/users/$userId'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/settings'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/charts'
    | '/api/admin/login'
    | '/api/admin/organizations'
    | '/api/admin/overview'
    | '/api/admin/stats'
    | '/api/admin/subscriptions'
    | '/api/admin/tunnels'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/checkout/paystack'
    | '/api/checkout/paystack-verify'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/dashboard/validate-ws-token'
    | '/api/dashboard/ws-token'
    | '/api/domain/verify-ownership'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/webhooks/paystack'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings'
    | '/$orgSlug/tunnels'
    | '/admin/organizations'
    | '/admin/users'
    | '/api/$orgSlug/domains/$domainId'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/requests/capture'
    | '/api/$orgSlug/requests/replay'
    | '/api/$orgSlug/stats/bandwidth'
    | '/api/$orgSlug/stats/overview'
    | '/api/$orgSlug/stats/protocol'
    | '/api/$orgSlug/stats/tunnel'
    | '/api/$orgSlug/subdomains/$subdomainId'
    | '/api/$orgSlug/tunnels/$tunnelId'
    | '/api/admin/organizations/$slug'
    | '/api/admin/users/$userId'
    | '/api/cli/login/status'
    | '/api/subscriptions/$orgSlug/cancel'
    | '/api/$orgSlug/domains'
    | '/api/$orgSlug/subdomains'
    | '/api/$orgSlug/tunnels'
    | '/api/$orgSlug/domains/$domainId/verify'
    | '/api/$orgSlug/tunnels/$tunnelId/stop'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/changelog'
    | '/contact'
    | '/email-templates'
    | '/login'
    | '/nextjs'
    | '/onboarding'
    | '/plugins'
    | '/pricing'
    | '/privacy'
    | '/report-bug'
    | '/select'
    | '/signup'
    | '/terms'
    | '/vite'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/settings'
    | '/$orgSlug/subdomains'
    | '/$orgSlug/tokens'
    | '/admin/actions'
    | '/admin/charts'
    | '/admin/subscriptions'
    | '/admin/tunnels'
    | '/api/health'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/admin/organizations/$slug'
    | '/admin/users/$userId'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/settings'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/charts'
    | '/api/admin/login'
    | '/api/admin/organizations'
    | '/api/admin/overview'
    | '/api/admin/stats'
    | '/api/admin/subscriptions'
    | '/api/admin/tunnels'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/checkout/paystack'
    | '/api/checkout/paystack-verify'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/dashboard/validate-ws-token'
    | '/api/dashboard/ws-token'
    | '/api/domain/verify-ownership'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/webhooks/paystack'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tunnels/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/api/$orgSlug/domains/$domainId'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/requests/capture'
    | '/api/$orgSlug/requests/replay'
    | '/api/$orgSlug/stats/bandwidth'
    | '/api/$orgSlug/stats/overview'
    | '/api/$orgSlug/stats/protocol'
    | '/api/$orgSlug/stats/tunnel'
    | '/api/$orgSlug/subdomains/$subdomainId'
    | '/api/$orgSlug/tunnels/$tunnelId'
    | '/api/admin/organizations/$slug'
    | '/api/admin/users/$userId'
    | '/api/cli/login/status'
    | '/api/subscriptions/$orgSlug/cancel'
    | '/api/$orgSlug/domains/'
    | '/api/$orgSlug/subdomains/'
    | '/api/$orgSlug/tunnels/'
    | '/api/$orgSlug/domains/$domainId/verify'
    | '/api/$orgSlug/tunnels/$tunnelId/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  EmailTemplatesRoute: typeof EmailTemplatesRoute
  LoginRoute: typeof LoginRoute
  NextjsRoute: typeof NextjsRoute
  OnboardingRoute: typeof OnboardingRoute
  PluginsRoute: typeof PluginsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportBugRoute: typeof ReportBugRoute
  SelectRoute: typeof SelectRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ViteRoute: typeof ViteRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSearchRoute: typeof ApiSearchRoute
  CliLoginRoute: typeof CliLoginRoute
  DocsSplatRoute: typeof DocsSplatRoute
  InternalDomainCheckRoute: typeof InternalDomainCheckRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  ApiOrgSlugAuthTokensRoute: typeof ApiOrgSlugAuthTokensRoute
  ApiOrgSlugRequestsRoute: typeof ApiOrgSlugRequestsRouteWithChildren
  ApiOrgSlugSettingsRoute: typeof ApiOrgSlugSettingsRoute
  ApiOrgSlugSubscriptionsRoute: typeof ApiOrgSlugSubscriptionsRoute
  ApiAdminChartsRoute: typeof ApiAdminChartsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminOrganizationsRoute: typeof ApiAdminOrganizationsRouteWithChildren
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminSubscriptionsRoute: typeof ApiAdminSubscriptionsRoute
  ApiAdminTunnelsRoute: typeof ApiAdminTunnelsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckoutPaystackRoute: typeof ApiCheckoutPaystackRoute
  ApiCheckoutPaystackVerifyRoute: typeof ApiCheckoutPaystackVerifyRoute
  ApiCheckoutPolarRoute: typeof ApiCheckoutPolarRoute
  ApiCliCompleteRoute: typeof ApiCliCompleteRoute
  ApiCliExchangeRoute: typeof ApiCliExchangeRoute
  ApiCliLoginRoute: typeof ApiCliLoginRouteWithChildren
  ApiDashboardValidateWsTokenRoute: typeof ApiDashboardValidateWsTokenRoute
  ApiDashboardWsTokenRoute: typeof ApiDashboardWsTokenRoute
  ApiDomainVerifyOwnershipRoute: typeof ApiDomainVerifyOwnershipRoute
  ApiMeOrgsRoute: typeof ApiMeOrgsRoute
  ApiOrganizationsCheckSlugRoute: typeof ApiOrganizationsCheckSlugRoute
  ApiTunnelAuthRoute: typeof ApiTunnelAuthRoute
  ApiTunnelCheckSubdomainRoute: typeof ApiTunnelCheckSubdomainRoute
  ApiTunnelRegisterRoute: typeof ApiTunnelRegisterRoute
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
  ApiOrgSlugDomainsDomainIdRoute: typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  ApiOrgSlugPortalPolarRoute: typeof ApiOrgSlugPortalPolarRoute
  ApiOrgSlugStatsBandwidthRoute: typeof ApiOrgSlugStatsBandwidthRoute
  ApiOrgSlugStatsOverviewRoute: typeof ApiOrgSlugStatsOverviewRoute
  ApiOrgSlugStatsProtocolRoute: typeof ApiOrgSlugStatsProtocolRoute
  ApiOrgSlugStatsTunnelRoute: typeof ApiOrgSlugStatsTunnelRoute
  ApiOrgSlugSubdomainsSubdomainIdRoute: typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  ApiOrgSlugTunnelsTunnelIdRoute: typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  ApiSubscriptionsOrgSlugCancelRoute: typeof ApiSubscriptionsOrgSlugCancelRoute
  ApiOrgSlugDomainsIndexRoute: typeof ApiOrgSlugDomainsIndexRoute
  ApiOrgSlugSubdomainsIndexRoute: typeof ApiOrgSlugSubdomainsIndexRoute
  ApiOrgSlugTunnelsIndexRoute: typeof ApiOrgSlugTunnelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vite': {
      id: '/vite'
      path: '/vite'
      fullPath: '/vite'
      preLoaderRoute: typeof ViteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-bug': {
      id: '/report-bug'
      path: '/report-bug'
      fullPath: '/report-bug'
      preLoaderRoute: typeof ReportBugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nextjs': {
      id: '/nextjs'
      path: '/nextjs'
      fullPath: '/nextjs'
      preLoaderRoute: typeof NextjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/domain-check': {
      id: '/internal/domain-check'
      path: '/internal/domain-check'
      fullPath: '/internal/domain-check'
      preLoaderRoute: typeof InternalDomainCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/login': {
      id: '/cli/login'
      path: '/cli/login'
      fullPath: '/cli/login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tunnels': {
      id: '/admin/tunnels'
      path: '/tunnels'
      fullPath: '/admin/tunnels'
      preLoaderRoute: typeof AdminTunnelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/charts': {
      id: '/admin/charts'
      path: '/charts'
      fullPath: '/admin/charts'
      preLoaderRoute: typeof AdminChartsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actions': {
      id: '/admin/actions'
      path: '/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminActionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$orgSlug/tokens': {
      id: '/$orgSlug/tokens'
      path: '/tokens'
      fullPath: '/$orgSlug/tokens'
      preLoaderRoute: typeof OrgSlugTokensRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/subdomains': {
      id: '/$orgSlug/subdomains'
      path: '/subdomains'
      fullPath: '/$orgSlug/subdomains'
      preLoaderRoute: typeof OrgSlugSubdomainsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/requests': {
      id: '/$orgSlug/requests'
      path: '/requests'
      fullPath: '/$orgSlug/requests'
      preLoaderRoute: typeof OrgSlugRequestsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/members': {
      id: '/$orgSlug/members'
      path: '/members'
      fullPath: '/$orgSlug/members'
      preLoaderRoute: typeof OrgSlugMembersRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/install': {
      id: '/$orgSlug/install'
      path: '/install'
      fullPath: '/$orgSlug/install'
      preLoaderRoute: typeof OrgSlugInstallRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/domains': {
      id: '/$orgSlug/domains'
      path: '/domains'
      fullPath: '/$orgSlug/domains'
      preLoaderRoute: typeof OrgSlugDomainsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/billing': {
      id: '/$orgSlug/billing'
      path: '/billing'
      fullPath: '/$orgSlug/billing'
      preLoaderRoute: typeof OrgSlugBillingRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$orgSlug/tunnels/': {
      id: '/$orgSlug/tunnels/'
      path: '/tunnels'
      fullPath: '/$orgSlug/tunnels'
      preLoaderRoute: typeof OrgSlugTunnelsIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/register': {
      id: '/api/tunnel/register'
      path: '/api/tunnel/register'
      fullPath: '/api/tunnel/register'
      preLoaderRoute: typeof ApiTunnelRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/check-subdomain': {
      id: '/api/tunnel/check-subdomain'
      path: '/api/tunnel/check-subdomain'
      fullPath: '/api/tunnel/check-subdomain'
      preLoaderRoute: typeof ApiTunnelCheckSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/auth': {
      id: '/api/tunnel/auth'
      path: '/api/tunnel/auth'
      fullPath: '/api/tunnel/auth'
      preLoaderRoute: typeof ApiTunnelAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/check-slug': {
      id: '/api/organizations/check-slug'
      path: '/api/organizations/check-slug'
      fullPath: '/api/organizations/check-slug'
      preLoaderRoute: typeof ApiOrganizationsCheckSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/orgs': {
      id: '/api/me/orgs'
      path: '/api/me/orgs'
      fullPath: '/api/me/orgs'
      preLoaderRoute: typeof ApiMeOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domain/verify-ownership': {
      id: '/api/domain/verify-ownership'
      path: '/api/domain/verify-ownership'
      fullPath: '/api/domain/verify-ownership'
      preLoaderRoute: typeof ApiDomainVerifyOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/ws-token': {
      id: '/api/dashboard/ws-token'
      path: '/api/dashboard/ws-token'
      fullPath: '/api/dashboard/ws-token'
      preLoaderRoute: typeof ApiDashboardWsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/validate-ws-token': {
      id: '/api/dashboard/validate-ws-token'
      path: '/api/dashboard/validate-ws-token'
      fullPath: '/api/dashboard/validate-ws-token'
      preLoaderRoute: typeof ApiDashboardValidateWsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/login': {
      id: '/api/cli/login'
      path: '/api/cli/login'
      fullPath: '/api/cli/login'
      preLoaderRoute: typeof ApiCliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/exchange': {
      id: '/api/cli/exchange'
      path: '/api/cli/exchange'
      fullPath: '/api/cli/exchange'
      preLoaderRoute: typeof ApiCliExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/complete': {
      id: '/api/cli/complete'
      path: '/api/cli/complete'
      fullPath: '/api/cli/complete'
      preLoaderRoute: typeof ApiCliCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/polar': {
      id: '/api/checkout/polar'
      path: '/api/checkout/polar'
      fullPath: '/api/checkout/polar'
      preLoaderRoute: typeof ApiCheckoutPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/paystack-verify': {
      id: '/api/checkout/paystack-verify'
      path: '/api/checkout/paystack-verify'
      fullPath: '/api/checkout/paystack-verify'
      preLoaderRoute: typeof ApiCheckoutPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/paystack': {
      id: '/api/checkout/paystack'
      path: '/api/checkout/paystack'
      fullPath: '/api/checkout/paystack'
      preLoaderRoute: typeof ApiCheckoutPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tunnels': {
      id: '/api/admin/tunnels'
      path: '/api/admin/tunnels'
      fullPath: '/api/admin/tunnels'
      preLoaderRoute: typeof ApiAdminTunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subscriptions': {
      id: '/api/admin/subscriptions'
      path: '/api/admin/subscriptions'
      fullPath: '/api/admin/subscriptions'
      preLoaderRoute: typeof ApiAdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/organizations': {
      id: '/api/admin/organizations'
      path: '/api/admin/organizations'
      fullPath: '/api/admin/organizations'
      preLoaderRoute: typeof ApiAdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/charts': {
      id: '/api/admin/charts'
      path: '/api/admin/charts'
      fullPath: '/api/admin/charts'
      preLoaderRoute: typeof ApiAdminChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subscriptions': {
      id: '/api/$orgSlug/subscriptions'
      path: '/api/$orgSlug/subscriptions'
      fullPath: '/api/$orgSlug/subscriptions'
      preLoaderRoute: typeof ApiOrgSlugSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/settings': {
      id: '/api/$orgSlug/settings'
      path: '/api/$orgSlug/settings'
      fullPath: '/api/$orgSlug/settings'
      preLoaderRoute: typeof ApiOrgSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/requests': {
      id: '/api/$orgSlug/requests'
      path: '/api/$orgSlug/requests'
      fullPath: '/api/$orgSlug/requests'
      preLoaderRoute: typeof ApiOrgSlugRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/auth-tokens': {
      id: '/api/$orgSlug/auth-tokens'
      path: '/api/$orgSlug/auth-tokens'
      fullPath: '/api/$orgSlug/auth-tokens'
      preLoaderRoute: typeof ApiOrgSlugAuthTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations/$slug': {
      id: '/admin/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/admin/organizations/$slug'
      preLoaderRoute: typeof AdminOrganizationsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$orgSlug/tunnels/$tunnelId': {
      id: '/$orgSlug/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/$orgSlug/tunnels/$tunnelId'
      preLoaderRoute: typeof OrgSlugTunnelsTunnelIdRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings/profile': {
      id: '/$orgSlug/settings/profile'
      path: '/profile'
      fullPath: '/$orgSlug/settings/profile'
      preLoaderRoute: typeof OrgSlugSettingsProfileRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/organization': {
      id: '/$orgSlug/settings/organization'
      path: '/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof OrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/api/$orgSlug/tunnels/': {
      id: '/api/$orgSlug/tunnels/'
      path: '/api/$orgSlug/tunnels'
      fullPath: '/api/$orgSlug/tunnels'
      preLoaderRoute: typeof ApiOrgSlugTunnelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subdomains/': {
      id: '/api/$orgSlug/subdomains/'
      path: '/api/$orgSlug/subdomains'
      fullPath: '/api/$orgSlug/subdomains'
      preLoaderRoute: typeof ApiOrgSlugSubdomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/domains/': {
      id: '/api/$orgSlug/domains/'
      path: '/api/$orgSlug/domains'
      fullPath: '/api/$orgSlug/domains'
      preLoaderRoute: typeof ApiOrgSlugDomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/$orgSlug/cancel': {
      id: '/api/subscriptions/$orgSlug/cancel'
      path: '/api/subscriptions/$orgSlug/cancel'
      fullPath: '/api/subscriptions/$orgSlug/cancel'
      preLoaderRoute: typeof ApiSubscriptionsOrgSlugCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/login/status': {
      id: '/api/cli/login/status'
      path: '/status'
      fullPath: '/api/cli/login/status'
      preLoaderRoute: typeof ApiCliLoginStatusRouteImport
      parentRoute: typeof ApiCliLoginRoute
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/organizations/$slug': {
      id: '/api/admin/organizations/$slug'
      path: '/$slug'
      fullPath: '/api/admin/organizations/$slug'
      preLoaderRoute: typeof ApiAdminOrganizationsSlugRouteImport
      parentRoute: typeof ApiAdminOrganizationsRoute
    }
    '/api/$orgSlug/tunnels/$tunnelId': {
      id: '/api/$orgSlug/tunnels/$tunnelId'
      path: '/api/$orgSlug/tunnels/$tunnelId'
      fullPath: '/api/$orgSlug/tunnels/$tunnelId'
      preLoaderRoute: typeof ApiOrgSlugTunnelsTunnelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subdomains/$subdomainId': {
      id: '/api/$orgSlug/subdomains/$subdomainId'
      path: '/api/$orgSlug/subdomains/$subdomainId'
      fullPath: '/api/$orgSlug/subdomains/$subdomainId'
      preLoaderRoute: typeof ApiOrgSlugSubdomainsSubdomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/tunnel': {
      id: '/api/$orgSlug/stats/tunnel'
      path: '/api/$orgSlug/stats/tunnel'
      fullPath: '/api/$orgSlug/stats/tunnel'
      preLoaderRoute: typeof ApiOrgSlugStatsTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/protocol': {
      id: '/api/$orgSlug/stats/protocol'
      path: '/api/$orgSlug/stats/protocol'
      fullPath: '/api/$orgSlug/stats/protocol'
      preLoaderRoute: typeof ApiOrgSlugStatsProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/overview': {
      id: '/api/$orgSlug/stats/overview'
      path: '/api/$orgSlug/stats/overview'
      fullPath: '/api/$orgSlug/stats/overview'
      preLoaderRoute: typeof ApiOrgSlugStatsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/bandwidth': {
      id: '/api/$orgSlug/stats/bandwidth'
      path: '/api/$orgSlug/stats/bandwidth'
      fullPath: '/api/$orgSlug/stats/bandwidth'
      preLoaderRoute: typeof ApiOrgSlugStatsBandwidthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/requests/replay': {
      id: '/api/$orgSlug/requests/replay'
      path: '/replay'
      fullPath: '/api/$orgSlug/requests/replay'
      preLoaderRoute: typeof ApiOrgSlugRequestsReplayRouteImport
      parentRoute: typeof ApiOrgSlugRequestsRoute
    }
    '/api/$orgSlug/requests/capture': {
      id: '/api/$orgSlug/requests/capture'
      path: '/capture'
      fullPath: '/api/$orgSlug/requests/capture'
      preLoaderRoute: typeof ApiOrgSlugRequestsCaptureRouteImport
      parentRoute: typeof ApiOrgSlugRequestsRoute
    }
    '/api/$orgSlug/portal/polar': {
      id: '/api/$orgSlug/portal/polar'
      path: '/api/$orgSlug/portal/polar'
      fullPath: '/api/$orgSlug/portal/polar'
      preLoaderRoute: typeof ApiOrgSlugPortalPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/domains/$domainId': {
      id: '/api/$orgSlug/domains/$domainId'
      path: '/api/$orgSlug/domains/$domainId'
      fullPath: '/api/$orgSlug/domains/$domainId'
      preLoaderRoute: typeof ApiOrgSlugDomainsDomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/tunnels/$tunnelId/stop': {
      id: '/api/$orgSlug/tunnels/$tunnelId/stop'
      path: '/stop'
      fullPath: '/api/$orgSlug/tunnels/$tunnelId/stop'
      preLoaderRoute: typeof ApiOrgSlugTunnelsTunnelIdStopRouteImport
      parentRoute: typeof ApiOrgSlugTunnelsTunnelIdRoute
    }
    '/api/$orgSlug/domains/$domainId/verify': {
      id: '/api/$orgSlug/domains/$domainId/verify'
      path: '/verify'
      fullPath: '/api/$orgSlug/domains/$domainId/verify'
      preLoaderRoute: typeof ApiOrgSlugDomainsDomainIdVerifyRouteImport
      parentRoute: typeof ApiOrgSlugDomainsDomainIdRoute
    }
  }
}

interface OrgSlugSettingsRouteChildren {
  OrgSlugSettingsOrganizationRoute: typeof OrgSlugSettingsOrganizationRoute
  OrgSlugSettingsProfileRoute: typeof OrgSlugSettingsProfileRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugSettingsRouteChildren: OrgSlugSettingsRouteChildren = {
  OrgSlugSettingsOrganizationRoute: OrgSlugSettingsOrganizationRoute,
  OrgSlugSettingsProfileRoute: OrgSlugSettingsProfileRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugSettingsRouteWithChildren = OrgSlugSettingsRoute._addFileChildren(
  OrgSlugSettingsRouteChildren,
)

interface OrgSlugRouteChildren {
  OrgSlugBillingRoute: typeof OrgSlugBillingRoute
  OrgSlugDomainsRoute: typeof OrgSlugDomainsRoute
  OrgSlugInstallRoute: typeof OrgSlugInstallRoute
  OrgSlugMembersRoute: typeof OrgSlugMembersRoute
  OrgSlugRequestsRoute: typeof OrgSlugRequestsRoute
  OrgSlugSettingsRoute: typeof OrgSlugSettingsRouteWithChildren
  OrgSlugSubdomainsRoute: typeof OrgSlugSubdomainsRoute
  OrgSlugTokensRoute: typeof OrgSlugTokensRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugTunnelsTunnelIdRoute: typeof OrgSlugTunnelsTunnelIdRoute
  OrgSlugTunnelsIndexRoute: typeof OrgSlugTunnelsIndexRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugBillingRoute: OrgSlugBillingRoute,
  OrgSlugDomainsRoute: OrgSlugDomainsRoute,
  OrgSlugInstallRoute: OrgSlugInstallRoute,
  OrgSlugMembersRoute: OrgSlugMembersRoute,
  OrgSlugRequestsRoute: OrgSlugRequestsRoute,
  OrgSlugSettingsRoute: OrgSlugSettingsRouteWithChildren,
  OrgSlugSubdomainsRoute: OrgSlugSubdomainsRoute,
  OrgSlugTokensRoute: OrgSlugTokensRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugTunnelsTunnelIdRoute: OrgSlugTunnelsTunnelIdRoute,
  OrgSlugTunnelsIndexRoute: OrgSlugTunnelsIndexRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

interface AdminRouteChildren {
  AdminActionsRoute: typeof AdminActionsRoute
  AdminChartsRoute: typeof AdminChartsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTunnelsRoute: typeof AdminTunnelsRoute
  AdminOrganizationsSlugRoute: typeof AdminOrganizationsSlugRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActionsRoute: AdminActionsRoute,
  AdminChartsRoute: AdminChartsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTunnelsRoute: AdminTunnelsRoute,
  AdminOrganizationsSlugRoute: AdminOrganizationsSlugRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiOrgSlugRequestsRouteChildren {
  ApiOrgSlugRequestsCaptureRoute: typeof ApiOrgSlugRequestsCaptureRoute
  ApiOrgSlugRequestsReplayRoute: typeof ApiOrgSlugRequestsReplayRoute
}

const ApiOrgSlugRequestsRouteChildren: ApiOrgSlugRequestsRouteChildren = {
  ApiOrgSlugRequestsCaptureRoute: ApiOrgSlugRequestsCaptureRoute,
  ApiOrgSlugRequestsReplayRoute: ApiOrgSlugRequestsReplayRoute,
}

const ApiOrgSlugRequestsRouteWithChildren =
  ApiOrgSlugRequestsRoute._addFileChildren(ApiOrgSlugRequestsRouteChildren)

interface ApiAdminOrganizationsRouteChildren {
  ApiAdminOrganizationsSlugRoute: typeof ApiAdminOrganizationsSlugRoute
}

const ApiAdminOrganizationsRouteChildren: ApiAdminOrganizationsRouteChildren = {
  ApiAdminOrganizationsSlugRoute: ApiAdminOrganizationsSlugRoute,
}

const ApiAdminOrganizationsRouteWithChildren =
  ApiAdminOrganizationsRoute._addFileChildren(
    ApiAdminOrganizationsRouteChildren,
  )

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiCliLoginRouteChildren {
  ApiCliLoginStatusRoute: typeof ApiCliLoginStatusRoute
}

const ApiCliLoginRouteChildren: ApiCliLoginRouteChildren = {
  ApiCliLoginStatusRoute: ApiCliLoginStatusRoute,
}

const ApiCliLoginRouteWithChildren = ApiCliLoginRoute._addFileChildren(
  ApiCliLoginRouteChildren,
)

interface ApiOrgSlugDomainsDomainIdRouteChildren {
  ApiOrgSlugDomainsDomainIdVerifyRoute: typeof ApiOrgSlugDomainsDomainIdVerifyRoute
}

const ApiOrgSlugDomainsDomainIdRouteChildren: ApiOrgSlugDomainsDomainIdRouteChildren =
  {
    ApiOrgSlugDomainsDomainIdVerifyRoute: ApiOrgSlugDomainsDomainIdVerifyRoute,
  }

const ApiOrgSlugDomainsDomainIdRouteWithChildren =
  ApiOrgSlugDomainsDomainIdRoute._addFileChildren(
    ApiOrgSlugDomainsDomainIdRouteChildren,
  )

interface ApiOrgSlugTunnelsTunnelIdRouteChildren {
  ApiOrgSlugTunnelsTunnelIdStopRoute: typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}

const ApiOrgSlugTunnelsTunnelIdRouteChildren: ApiOrgSlugTunnelsTunnelIdRouteChildren =
  {
    ApiOrgSlugTunnelsTunnelIdStopRoute: ApiOrgSlugTunnelsTunnelIdStopRoute,
  }

const ApiOrgSlugTunnelsTunnelIdRouteWithChildren =
  ApiOrgSlugTunnelsTunnelIdRoute._addFileChildren(
    ApiOrgSlugTunnelsTunnelIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  EmailTemplatesRoute: EmailTemplatesRoute,
  LoginRoute: LoginRoute,
  NextjsRoute: NextjsRoute,
  OnboardingRoute: OnboardingRoute,
  PluginsRoute: PluginsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReportBugRoute: ReportBugRoute,
  SelectRoute: SelectRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ViteRoute: ViteRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSearchRoute: ApiSearchRoute,
  CliLoginRoute: CliLoginRoute,
  DocsSplatRoute: DocsSplatRoute,
  InternalDomainCheckRoute: InternalDomainCheckRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  ApiOrgSlugAuthTokensRoute: ApiOrgSlugAuthTokensRoute,
  ApiOrgSlugRequestsRoute: ApiOrgSlugRequestsRouteWithChildren,
  ApiOrgSlugSettingsRoute: ApiOrgSlugSettingsRoute,
  ApiOrgSlugSubscriptionsRoute: ApiOrgSlugSubscriptionsRoute,
  ApiAdminChartsRoute: ApiAdminChartsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminOrganizationsRoute: ApiAdminOrganizationsRouteWithChildren,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminSubscriptionsRoute: ApiAdminSubscriptionsRoute,
  ApiAdminTunnelsRoute: ApiAdminTunnelsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckoutPaystackRoute: ApiCheckoutPaystackRoute,
  ApiCheckoutPaystackVerifyRoute: ApiCheckoutPaystackVerifyRoute,
  ApiCheckoutPolarRoute: ApiCheckoutPolarRoute,
  ApiCliCompleteRoute: ApiCliCompleteRoute,
  ApiCliExchangeRoute: ApiCliExchangeRoute,
  ApiCliLoginRoute: ApiCliLoginRouteWithChildren,
  ApiDashboardValidateWsTokenRoute: ApiDashboardValidateWsTokenRoute,
  ApiDashboardWsTokenRoute: ApiDashboardWsTokenRoute,
  ApiDomainVerifyOwnershipRoute: ApiDomainVerifyOwnershipRoute,
  ApiMeOrgsRoute: ApiMeOrgsRoute,
  ApiOrganizationsCheckSlugRoute: ApiOrganizationsCheckSlugRoute,
  ApiTunnelAuthRoute: ApiTunnelAuthRoute,
  ApiTunnelCheckSubdomainRoute: ApiTunnelCheckSubdomainRoute,
  ApiTunnelRegisterRoute: ApiTunnelRegisterRoute,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
  ApiOrgSlugDomainsDomainIdRoute: ApiOrgSlugDomainsDomainIdRouteWithChildren,
  ApiOrgSlugPortalPolarRoute: ApiOrgSlugPortalPolarRoute,
  ApiOrgSlugStatsBandwidthRoute: ApiOrgSlugStatsBandwidthRoute,
  ApiOrgSlugStatsOverviewRoute: ApiOrgSlugStatsOverviewRoute,
  ApiOrgSlugStatsProtocolRoute: ApiOrgSlugStatsProtocolRoute,
  ApiOrgSlugStatsTunnelRoute: ApiOrgSlugStatsTunnelRoute,
  ApiOrgSlugSubdomainsSubdomainIdRoute: ApiOrgSlugSubdomainsSubdomainIdRoute,
  ApiOrgSlugTunnelsTunnelIdRoute: ApiOrgSlugTunnelsTunnelIdRouteWithChildren,
  ApiSubscriptionsOrgSlugCancelRoute: ApiSubscriptionsOrgSlugCancelRoute,
  ApiOrgSlugDomainsIndexRoute: ApiOrgSlugDomainsIndexRoute,
  ApiOrgSlugSubdomainsIndexRoute: ApiOrgSlugSubdomainsIndexRoute,
  ApiOrgSlugTunnelsIndexRoute: ApiOrgSlugTunnelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
