/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectRouteImport } from './routes/select'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept'
import { Route as InternalDomainCheckRouteImport } from './routes/internal/domain-check'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as CliLoginRouteImport } from './routes/cli.login'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as OrgSlugTokensRouteImport } from './routes/$orgSlug/tokens'
import { Route as OrgSlugSubdomainsRouteImport } from './routes/$orgSlug/subdomains'
import { Route as OrgSlugSettingsRouteImport } from './routes/$orgSlug/settings'
import { Route as OrgSlugRequestsRouteImport } from './routes/$orgSlug/requests'
import { Route as OrgSlugMembersRouteImport } from './routes/$orgSlug/members'
import { Route as OrgSlugInstallRouteImport } from './routes/$orgSlug/install'
import { Route as OrgSlugDomainsRouteImport } from './routes/$orgSlug/domains'
import { Route as OrgSlugBillingRouteImport } from './routes/$orgSlug/billing'
import { Route as OrgSlugTunnelsIndexRouteImport } from './routes/$orgSlug/tunnels/index'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiTunnelRegisterRouteImport } from './routes/api/tunnel/register'
import { Route as ApiTunnelCheckSubdomainRouteImport } from './routes/api/tunnel/check-subdomain'
import { Route as ApiTunnelAuthRouteImport } from './routes/api/tunnel/auth'
import { Route as ApiSubscriptionsOrganizationIdRouteImport } from './routes/api/subscriptions/$organizationId'
import { Route as ApiOrganizationsCheckSlugRouteImport } from './routes/api/organizations/check-slug'
import { Route as ApiMeOrgsRouteImport } from './routes/api/me/orgs'
import { Route as ApiDomainVerifyOwnershipRouteImport } from './routes/api/domain/verify-ownership'
import { Route as ApiCliLoginRouteImport } from './routes/api/cli/login'
import { Route as ApiCliExchangeRouteImport } from './routes/api/cli/exchange'
import { Route as ApiCliCompleteRouteImport } from './routes/api/cli/complete'
import { Route as ApiCheckoutPolarRouteImport } from './routes/api/checkout/polar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiOrgSlugSubscriptionsRouteImport } from './routes/api/$orgSlug/subscriptions'
import { Route as ApiOrgSlugSettingsRouteImport } from './routes/api/$orgSlug/settings'
import { Route as ApiOrgSlugRequestsRouteImport } from './routes/api/$orgSlug/requests'
import { Route as ApiOrgSlugAuthTokensRouteImport } from './routes/api/$orgSlug/auth-tokens'
import { Route as OrgSlugTunnelsTunnelIdRouteImport } from './routes/$orgSlug/tunnels/$tunnelId'
import { Route as OrgSlugSettingsProfileRouteImport } from './routes/$orgSlug/settings/profile'
import { Route as OrgSlugSettingsOrganizationRouteImport } from './routes/$orgSlug/settings/organization'
import { Route as ApiOrgSlugTunnelsIndexRouteImport } from './routes/api/$orgSlug/tunnels/index'
import { Route as ApiOrgSlugSubdomainsIndexRouteImport } from './routes/api/$orgSlug/subdomains/index'
import { Route as ApiOrgSlugDomainsIndexRouteImport } from './routes/api/$orgSlug/domains/index'
import { Route as ApiCliLoginStatusRouteImport } from './routes/api/cli/login/status'
import { Route as ApiOrgSlugTunnelsTunnelIdRouteImport } from './routes/api/$orgSlug/tunnels/$tunnelId'
import { Route as ApiOrgSlugSubdomainsSubdomainIdRouteImport } from './routes/api/$orgSlug/subdomains/$subdomainId'
import { Route as ApiOrgSlugStatsTunnelRouteImport } from './routes/api/$orgSlug/stats/tunnel'
import { Route as ApiOrgSlugStatsProtocolRouteImport } from './routes/api/$orgSlug/stats/protocol'
import { Route as ApiOrgSlugStatsOverviewRouteImport } from './routes/api/$orgSlug/stats/overview'
import { Route as ApiOrgSlugStatsBandwidthRouteImport } from './routes/api/$orgSlug/stats/bandwidth'
import { Route as ApiOrgSlugRequestsReplayRouteImport } from './routes/api/$orgSlug/requests/replay'
import { Route as ApiOrgSlugRequestsCaptureRouteImport } from './routes/api/$orgSlug/requests/capture'
import { Route as ApiOrgSlugPortalPolarRouteImport } from './routes/api/$orgSlug/portal/polar'
import { Route as ApiOrgSlugDomainsDomainIdRouteImport } from './routes/api/$orgSlug/domains/$domainId'
import { Route as ApiOrgSlugTunnelsTunnelIdStopRouteImport } from './routes/api/$orgSlug/tunnels/$tunnelId.stop'
import { Route as ApiOrgSlugDomainsDomainIdVerifyRouteImport } from './routes/api/$orgSlug/domains/$domainId.verify'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalDomainCheckRoute = InternalDomainCheckRouteImport.update({
  id: '/internal/domain-check',
  path: '/internal/domain-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli/login',
  path: '/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugTokensRoute = OrgSlugTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSubdomainsRoute = OrgSlugSubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsRoute = OrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugRequestsRoute = OrgSlugRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugMembersRoute = OrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugInstallRoute = OrgSlugInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugDomainsRoute = OrgSlugDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugBillingRoute = OrgSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugTunnelsIndexRoute = OrgSlugTunnelsIndexRouteImport.update({
  id: '/tunnels/',
  path: '/tunnels/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelRegisterRoute = ApiTunnelRegisterRouteImport.update({
  id: '/api/tunnel/register',
  path: '/api/tunnel/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelCheckSubdomainRoute = ApiTunnelCheckSubdomainRouteImport.update({
  id: '/api/tunnel/check-subdomain',
  path: '/api/tunnel/check-subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelAuthRoute = ApiTunnelAuthRouteImport.update({
  id: '/api/tunnel/auth',
  path: '/api/tunnel/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsOrganizationIdRoute =
  ApiSubscriptionsOrganizationIdRouteImport.update({
    id: '/api/subscriptions/$organizationId',
    path: '/api/subscriptions/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsCheckSlugRoute =
  ApiOrganizationsCheckSlugRouteImport.update({
    id: '/api/organizations/check-slug',
    path: '/api/organizations/check-slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeOrgsRoute = ApiMeOrgsRouteImport.update({
  id: '/api/me/orgs',
  path: '/api/me/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainVerifyOwnershipRoute =
  ApiDomainVerifyOwnershipRouteImport.update({
    id: '/api/domain/verify-ownership',
    path: '/api/domain/verify-ownership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliLoginRoute = ApiCliLoginRouteImport.update({
  id: '/api/cli/login',
  path: '/api/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliExchangeRoute = ApiCliExchangeRouteImport.update({
  id: '/api/cli/exchange',
  path: '/api/cli/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliCompleteRoute = ApiCliCompleteRouteImport.update({
  id: '/api/cli/complete',
  path: '/api/cli/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutPolarRoute = ApiCheckoutPolarRouteImport.update({
  id: '/api/checkout/polar',
  path: '/api/checkout/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSubscriptionsRoute = ApiOrgSlugSubscriptionsRouteImport.update({
  id: '/api/$orgSlug/subscriptions',
  path: '/api/$orgSlug/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSettingsRoute = ApiOrgSlugSettingsRouteImport.update({
  id: '/api/$orgSlug/settings',
  path: '/api/$orgSlug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugRequestsRoute = ApiOrgSlugRequestsRouteImport.update({
  id: '/api/$orgSlug/requests',
  path: '/api/$orgSlug/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugAuthTokensRoute = ApiOrgSlugAuthTokensRouteImport.update({
  id: '/api/$orgSlug/auth-tokens',
  path: '/api/$orgSlug/auth-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugTunnelsTunnelIdRoute = OrgSlugTunnelsTunnelIdRouteImport.update({
  id: '/tunnels/$tunnelId',
  path: '/tunnels/$tunnelId',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsProfileRoute = OrgSlugSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const OrgSlugSettingsOrganizationRoute =
  OrgSlugSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgSlugSettingsRoute,
  } as any)
const ApiOrgSlugTunnelsIndexRoute = ApiOrgSlugTunnelsIndexRouteImport.update({
  id: '/api/$orgSlug/tunnels/',
  path: '/api/$orgSlug/tunnels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSubdomainsIndexRoute =
  ApiOrgSlugSubdomainsIndexRouteImport.update({
    id: '/api/$orgSlug/subdomains/',
    path: '/api/$orgSlug/subdomains/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugDomainsIndexRoute = ApiOrgSlugDomainsIndexRouteImport.update({
  id: '/api/$orgSlug/domains/',
  path: '/api/$orgSlug/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliLoginStatusRoute = ApiCliLoginStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiCliLoginRoute,
} as any)
const ApiOrgSlugTunnelsTunnelIdRoute =
  ApiOrgSlugTunnelsTunnelIdRouteImport.update({
    id: '/api/$orgSlug/tunnels/$tunnelId',
    path: '/api/$orgSlug/tunnels/$tunnelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugSubdomainsSubdomainIdRoute =
  ApiOrgSlugSubdomainsSubdomainIdRouteImport.update({
    id: '/api/$orgSlug/subdomains/$subdomainId',
    path: '/api/$orgSlug/subdomains/$subdomainId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugStatsTunnelRoute = ApiOrgSlugStatsTunnelRouteImport.update({
  id: '/api/$orgSlug/stats/tunnel',
  path: '/api/$orgSlug/stats/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugStatsProtocolRoute = ApiOrgSlugStatsProtocolRouteImport.update({
  id: '/api/$orgSlug/stats/protocol',
  path: '/api/$orgSlug/stats/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugStatsOverviewRoute = ApiOrgSlugStatsOverviewRouteImport.update({
  id: '/api/$orgSlug/stats/overview',
  path: '/api/$orgSlug/stats/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugStatsBandwidthRoute =
  ApiOrgSlugStatsBandwidthRouteImport.update({
    id: '/api/$orgSlug/stats/bandwidth',
    path: '/api/$orgSlug/stats/bandwidth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugRequestsReplayRoute =
  ApiOrgSlugRequestsReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => ApiOrgSlugRequestsRoute,
  } as any)
const ApiOrgSlugRequestsCaptureRoute =
  ApiOrgSlugRequestsCaptureRouteImport.update({
    id: '/capture',
    path: '/capture',
    getParentRoute: () => ApiOrgSlugRequestsRoute,
  } as any)
const ApiOrgSlugPortalPolarRoute = ApiOrgSlugPortalPolarRouteImport.update({
  id: '/api/$orgSlug/portal/polar',
  path: '/api/$orgSlug/portal/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugDomainsDomainIdRoute =
  ApiOrgSlugDomainsDomainIdRouteImport.update({
    id: '/api/$orgSlug/domains/$domainId',
    path: '/api/$orgSlug/domains/$domainId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugTunnelsTunnelIdStopRoute =
  ApiOrgSlugTunnelsTunnelIdStopRouteImport.update({
    id: '/stop',
    path: '/stop',
    getParentRoute: () => ApiOrgSlugTunnelsTunnelIdRoute,
  } as any)
const ApiOrgSlugDomainsDomainIdVerifyRoute =
  ApiOrgSlugDomainsDomainIdVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => ApiOrgSlugDomainsDomainIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/subdomains': typeof OrgSlugSubdomainsRoute
  '/$orgSlug/tokens': typeof OrgSlugTokensRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRouteWithChildren
  '/api/$orgSlug/settings': typeof ApiOrgSlugSettingsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels': typeof OrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId': typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/requests/capture': typeof ApiOrgSlugRequestsCaptureRoute
  '/api/$orgSlug/requests/replay': typeof ApiOrgSlugRequestsReplayRoute
  '/api/$orgSlug/stats/bandwidth': typeof ApiOrgSlugStatsBandwidthRoute
  '/api/$orgSlug/stats/overview': typeof ApiOrgSlugStatsOverviewRoute
  '/api/$orgSlug/stats/protocol': typeof ApiOrgSlugStatsProtocolRoute
  '/api/$orgSlug/stats/tunnel': typeof ApiOrgSlugStatsTunnelRoute
  '/api/$orgSlug/subdomains/$subdomainId': typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  '/api/$orgSlug/tunnels/$tunnelId': typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/$orgSlug/domains': typeof ApiOrgSlugDomainsIndexRoute
  '/api/$orgSlug/subdomains': typeof ApiOrgSlugSubdomainsIndexRoute
  '/api/$orgSlug/tunnels': typeof ApiOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId/verify': typeof ApiOrgSlugDomainsDomainIdVerifyRoute
  '/api/$orgSlug/tunnels/$tunnelId/stop': typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/subdomains': typeof OrgSlugSubdomainsRoute
  '/$orgSlug/tokens': typeof OrgSlugTokensRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRouteWithChildren
  '/api/$orgSlug/settings': typeof ApiOrgSlugSettingsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels': typeof OrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId': typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/requests/capture': typeof ApiOrgSlugRequestsCaptureRoute
  '/api/$orgSlug/requests/replay': typeof ApiOrgSlugRequestsReplayRoute
  '/api/$orgSlug/stats/bandwidth': typeof ApiOrgSlugStatsBandwidthRoute
  '/api/$orgSlug/stats/overview': typeof ApiOrgSlugStatsOverviewRoute
  '/api/$orgSlug/stats/protocol': typeof ApiOrgSlugStatsProtocolRoute
  '/api/$orgSlug/stats/tunnel': typeof ApiOrgSlugStatsTunnelRoute
  '/api/$orgSlug/subdomains/$subdomainId': typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  '/api/$orgSlug/tunnels/$tunnelId': typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/$orgSlug/domains': typeof ApiOrgSlugDomainsIndexRoute
  '/api/$orgSlug/subdomains': typeof ApiOrgSlugSubdomainsIndexRoute
  '/api/$orgSlug/tunnels': typeof ApiOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId/verify': typeof ApiOrgSlugDomainsDomainIdVerifyRoute
  '/api/$orgSlug/tunnels/$tunnelId/stop': typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/subdomains': typeof OrgSlugSubdomainsRoute
  '/$orgSlug/tokens': typeof OrgSlugTokensRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRouteWithChildren
  '/api/$orgSlug/settings': typeof ApiOrgSlugSettingsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels/': typeof OrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId': typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/requests/capture': typeof ApiOrgSlugRequestsCaptureRoute
  '/api/$orgSlug/requests/replay': typeof ApiOrgSlugRequestsReplayRoute
  '/api/$orgSlug/stats/bandwidth': typeof ApiOrgSlugStatsBandwidthRoute
  '/api/$orgSlug/stats/overview': typeof ApiOrgSlugStatsOverviewRoute
  '/api/$orgSlug/stats/protocol': typeof ApiOrgSlugStatsProtocolRoute
  '/api/$orgSlug/stats/tunnel': typeof ApiOrgSlugStatsTunnelRoute
  '/api/$orgSlug/subdomains/$subdomainId': typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  '/api/$orgSlug/tunnels/$tunnelId': typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/$orgSlug/domains/': typeof ApiOrgSlugDomainsIndexRoute
  '/api/$orgSlug/subdomains/': typeof ApiOrgSlugSubdomainsIndexRoute
  '/api/$orgSlug/tunnels/': typeof ApiOrgSlugTunnelsIndexRoute
  '/api/$orgSlug/domains/$domainId/verify': typeof ApiOrgSlugDomainsDomainIdVerifyRoute
  '/api/$orgSlug/tunnels/$tunnelId/stop': typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/email-templates'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/select'
    | '/signup'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/settings'
    | '/$orgSlug/subdomains'
    | '/$orgSlug/tokens'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/settings'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tunnels'
    | '/api/$orgSlug/domains/$domainId'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/requests/capture'
    | '/api/$orgSlug/requests/replay'
    | '/api/$orgSlug/stats/bandwidth'
    | '/api/$orgSlug/stats/overview'
    | '/api/$orgSlug/stats/protocol'
    | '/api/$orgSlug/stats/tunnel'
    | '/api/$orgSlug/subdomains/$subdomainId'
    | '/api/$orgSlug/tunnels/$tunnelId'
    | '/api/cli/login/status'
    | '/api/$orgSlug/domains'
    | '/api/$orgSlug/subdomains'
    | '/api/$orgSlug/tunnels'
    | '/api/$orgSlug/domains/$domainId/verify'
    | '/api/$orgSlug/tunnels/$tunnelId/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/email-templates'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/select'
    | '/signup'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/subdomains'
    | '/$orgSlug/tokens'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/settings'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings'
    | '/$orgSlug/tunnels'
    | '/api/$orgSlug/domains/$domainId'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/requests/capture'
    | '/api/$orgSlug/requests/replay'
    | '/api/$orgSlug/stats/bandwidth'
    | '/api/$orgSlug/stats/overview'
    | '/api/$orgSlug/stats/protocol'
    | '/api/$orgSlug/stats/tunnel'
    | '/api/$orgSlug/subdomains/$subdomainId'
    | '/api/$orgSlug/tunnels/$tunnelId'
    | '/api/cli/login/status'
    | '/api/$orgSlug/domains'
    | '/api/$orgSlug/subdomains'
    | '/api/$orgSlug/tunnels'
    | '/api/$orgSlug/domains/$domainId/verify'
    | '/api/$orgSlug/tunnels/$tunnelId/stop'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/email-templates'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/select'
    | '/signup'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/settings'
    | '/$orgSlug/subdomains'
    | '/$orgSlug/tokens'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/settings'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tunnels/'
    | '/api/$orgSlug/domains/$domainId'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/requests/capture'
    | '/api/$orgSlug/requests/replay'
    | '/api/$orgSlug/stats/bandwidth'
    | '/api/$orgSlug/stats/overview'
    | '/api/$orgSlug/stats/protocol'
    | '/api/$orgSlug/stats/tunnel'
    | '/api/$orgSlug/subdomains/$subdomainId'
    | '/api/$orgSlug/tunnels/$tunnelId'
    | '/api/cli/login/status'
    | '/api/$orgSlug/domains/'
    | '/api/$orgSlug/subdomains/'
    | '/api/$orgSlug/tunnels/'
    | '/api/$orgSlug/domains/$domainId/verify'
    | '/api/$orgSlug/tunnels/$tunnelId/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  AdminRoute: typeof AdminRoute
  EmailTemplatesRoute: typeof EmailTemplatesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SelectRoute: typeof SelectRoute
  SignupRoute: typeof SignupRoute
  ApiSearchRoute: typeof ApiSearchRoute
  CliLoginRoute: typeof CliLoginRoute
  DocsSplatRoute: typeof DocsSplatRoute
  InternalDomainCheckRoute: typeof InternalDomainCheckRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  ApiOrgSlugAuthTokensRoute: typeof ApiOrgSlugAuthTokensRoute
  ApiOrgSlugRequestsRoute: typeof ApiOrgSlugRequestsRouteWithChildren
  ApiOrgSlugSettingsRoute: typeof ApiOrgSlugSettingsRoute
  ApiOrgSlugSubscriptionsRoute: typeof ApiOrgSlugSubscriptionsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckoutPolarRoute: typeof ApiCheckoutPolarRoute
  ApiCliCompleteRoute: typeof ApiCliCompleteRoute
  ApiCliExchangeRoute: typeof ApiCliExchangeRoute
  ApiCliLoginRoute: typeof ApiCliLoginRouteWithChildren
  ApiDomainVerifyOwnershipRoute: typeof ApiDomainVerifyOwnershipRoute
  ApiMeOrgsRoute: typeof ApiMeOrgsRoute
  ApiOrganizationsCheckSlugRoute: typeof ApiOrganizationsCheckSlugRoute
  ApiSubscriptionsOrganizationIdRoute: typeof ApiSubscriptionsOrganizationIdRoute
  ApiTunnelAuthRoute: typeof ApiTunnelAuthRoute
  ApiTunnelCheckSubdomainRoute: typeof ApiTunnelCheckSubdomainRoute
  ApiTunnelRegisterRoute: typeof ApiTunnelRegisterRoute
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
  ApiOrgSlugDomainsDomainIdRoute: typeof ApiOrgSlugDomainsDomainIdRouteWithChildren
  ApiOrgSlugPortalPolarRoute: typeof ApiOrgSlugPortalPolarRoute
  ApiOrgSlugStatsBandwidthRoute: typeof ApiOrgSlugStatsBandwidthRoute
  ApiOrgSlugStatsOverviewRoute: typeof ApiOrgSlugStatsOverviewRoute
  ApiOrgSlugStatsProtocolRoute: typeof ApiOrgSlugStatsProtocolRoute
  ApiOrgSlugStatsTunnelRoute: typeof ApiOrgSlugStatsTunnelRoute
  ApiOrgSlugSubdomainsSubdomainIdRoute: typeof ApiOrgSlugSubdomainsSubdomainIdRoute
  ApiOrgSlugTunnelsTunnelIdRoute: typeof ApiOrgSlugTunnelsTunnelIdRouteWithChildren
  ApiOrgSlugDomainsIndexRoute: typeof ApiOrgSlugDomainsIndexRoute
  ApiOrgSlugSubdomainsIndexRoute: typeof ApiOrgSlugSubdomainsIndexRoute
  ApiOrgSlugTunnelsIndexRoute: typeof ApiOrgSlugTunnelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/domain-check': {
      id: '/internal/domain-check'
      path: '/internal/domain-check'
      fullPath: '/internal/domain-check'
      preLoaderRoute: typeof InternalDomainCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/login': {
      id: '/cli/login'
      path: '/cli/login'
      fullPath: '/cli/login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/tokens': {
      id: '/$orgSlug/tokens'
      path: '/tokens'
      fullPath: '/$orgSlug/tokens'
      preLoaderRoute: typeof OrgSlugTokensRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/subdomains': {
      id: '/$orgSlug/subdomains'
      path: '/subdomains'
      fullPath: '/$orgSlug/subdomains'
      preLoaderRoute: typeof OrgSlugSubdomainsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/requests': {
      id: '/$orgSlug/requests'
      path: '/requests'
      fullPath: '/$orgSlug/requests'
      preLoaderRoute: typeof OrgSlugRequestsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/members': {
      id: '/$orgSlug/members'
      path: '/members'
      fullPath: '/$orgSlug/members'
      preLoaderRoute: typeof OrgSlugMembersRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/install': {
      id: '/$orgSlug/install'
      path: '/install'
      fullPath: '/$orgSlug/install'
      preLoaderRoute: typeof OrgSlugInstallRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/domains': {
      id: '/$orgSlug/domains'
      path: '/domains'
      fullPath: '/$orgSlug/domains'
      preLoaderRoute: typeof OrgSlugDomainsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/billing': {
      id: '/$orgSlug/billing'
      path: '/billing'
      fullPath: '/$orgSlug/billing'
      preLoaderRoute: typeof OrgSlugBillingRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/tunnels/': {
      id: '/$orgSlug/tunnels/'
      path: '/tunnels'
      fullPath: '/$orgSlug/tunnels'
      preLoaderRoute: typeof OrgSlugTunnelsIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/register': {
      id: '/api/tunnel/register'
      path: '/api/tunnel/register'
      fullPath: '/api/tunnel/register'
      preLoaderRoute: typeof ApiTunnelRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/check-subdomain': {
      id: '/api/tunnel/check-subdomain'
      path: '/api/tunnel/check-subdomain'
      fullPath: '/api/tunnel/check-subdomain'
      preLoaderRoute: typeof ApiTunnelCheckSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/auth': {
      id: '/api/tunnel/auth'
      path: '/api/tunnel/auth'
      fullPath: '/api/tunnel/auth'
      preLoaderRoute: typeof ApiTunnelAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/$organizationId': {
      id: '/api/subscriptions/$organizationId'
      path: '/api/subscriptions/$organizationId'
      fullPath: '/api/subscriptions/$organizationId'
      preLoaderRoute: typeof ApiSubscriptionsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/check-slug': {
      id: '/api/organizations/check-slug'
      path: '/api/organizations/check-slug'
      fullPath: '/api/organizations/check-slug'
      preLoaderRoute: typeof ApiOrganizationsCheckSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/orgs': {
      id: '/api/me/orgs'
      path: '/api/me/orgs'
      fullPath: '/api/me/orgs'
      preLoaderRoute: typeof ApiMeOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domain/verify-ownership': {
      id: '/api/domain/verify-ownership'
      path: '/api/domain/verify-ownership'
      fullPath: '/api/domain/verify-ownership'
      preLoaderRoute: typeof ApiDomainVerifyOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/login': {
      id: '/api/cli/login'
      path: '/api/cli/login'
      fullPath: '/api/cli/login'
      preLoaderRoute: typeof ApiCliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/exchange': {
      id: '/api/cli/exchange'
      path: '/api/cli/exchange'
      fullPath: '/api/cli/exchange'
      preLoaderRoute: typeof ApiCliExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/complete': {
      id: '/api/cli/complete'
      path: '/api/cli/complete'
      fullPath: '/api/cli/complete'
      preLoaderRoute: typeof ApiCliCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/polar': {
      id: '/api/checkout/polar'
      path: '/api/checkout/polar'
      fullPath: '/api/checkout/polar'
      preLoaderRoute: typeof ApiCheckoutPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subscriptions': {
      id: '/api/$orgSlug/subscriptions'
      path: '/api/$orgSlug/subscriptions'
      fullPath: '/api/$orgSlug/subscriptions'
      preLoaderRoute: typeof ApiOrgSlugSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/settings': {
      id: '/api/$orgSlug/settings'
      path: '/api/$orgSlug/settings'
      fullPath: '/api/$orgSlug/settings'
      preLoaderRoute: typeof ApiOrgSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/requests': {
      id: '/api/$orgSlug/requests'
      path: '/api/$orgSlug/requests'
      fullPath: '/api/$orgSlug/requests'
      preLoaderRoute: typeof ApiOrgSlugRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/auth-tokens': {
      id: '/api/$orgSlug/auth-tokens'
      path: '/api/$orgSlug/auth-tokens'
      fullPath: '/api/$orgSlug/auth-tokens'
      preLoaderRoute: typeof ApiOrgSlugAuthTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/tunnels/$tunnelId': {
      id: '/$orgSlug/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/$orgSlug/tunnels/$tunnelId'
      preLoaderRoute: typeof OrgSlugTunnelsTunnelIdRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings/profile': {
      id: '/$orgSlug/settings/profile'
      path: '/profile'
      fullPath: '/$orgSlug/settings/profile'
      preLoaderRoute: typeof OrgSlugSettingsProfileRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/organization': {
      id: '/$orgSlug/settings/organization'
      path: '/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof OrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/api/$orgSlug/tunnels/': {
      id: '/api/$orgSlug/tunnels/'
      path: '/api/$orgSlug/tunnels'
      fullPath: '/api/$orgSlug/tunnels'
      preLoaderRoute: typeof ApiOrgSlugTunnelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subdomains/': {
      id: '/api/$orgSlug/subdomains/'
      path: '/api/$orgSlug/subdomains'
      fullPath: '/api/$orgSlug/subdomains'
      preLoaderRoute: typeof ApiOrgSlugSubdomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/domains/': {
      id: '/api/$orgSlug/domains/'
      path: '/api/$orgSlug/domains'
      fullPath: '/api/$orgSlug/domains'
      preLoaderRoute: typeof ApiOrgSlugDomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/login/status': {
      id: '/api/cli/login/status'
      path: '/status'
      fullPath: '/api/cli/login/status'
      preLoaderRoute: typeof ApiCliLoginStatusRouteImport
      parentRoute: typeof ApiCliLoginRoute
    }
    '/api/$orgSlug/tunnels/$tunnelId': {
      id: '/api/$orgSlug/tunnels/$tunnelId'
      path: '/api/$orgSlug/tunnels/$tunnelId'
      fullPath: '/api/$orgSlug/tunnels/$tunnelId'
      preLoaderRoute: typeof ApiOrgSlugTunnelsTunnelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subdomains/$subdomainId': {
      id: '/api/$orgSlug/subdomains/$subdomainId'
      path: '/api/$orgSlug/subdomains/$subdomainId'
      fullPath: '/api/$orgSlug/subdomains/$subdomainId'
      preLoaderRoute: typeof ApiOrgSlugSubdomainsSubdomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/tunnel': {
      id: '/api/$orgSlug/stats/tunnel'
      path: '/api/$orgSlug/stats/tunnel'
      fullPath: '/api/$orgSlug/stats/tunnel'
      preLoaderRoute: typeof ApiOrgSlugStatsTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/protocol': {
      id: '/api/$orgSlug/stats/protocol'
      path: '/api/$orgSlug/stats/protocol'
      fullPath: '/api/$orgSlug/stats/protocol'
      preLoaderRoute: typeof ApiOrgSlugStatsProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/overview': {
      id: '/api/$orgSlug/stats/overview'
      path: '/api/$orgSlug/stats/overview'
      fullPath: '/api/$orgSlug/stats/overview'
      preLoaderRoute: typeof ApiOrgSlugStatsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/stats/bandwidth': {
      id: '/api/$orgSlug/stats/bandwidth'
      path: '/api/$orgSlug/stats/bandwidth'
      fullPath: '/api/$orgSlug/stats/bandwidth'
      preLoaderRoute: typeof ApiOrgSlugStatsBandwidthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/requests/replay': {
      id: '/api/$orgSlug/requests/replay'
      path: '/replay'
      fullPath: '/api/$orgSlug/requests/replay'
      preLoaderRoute: typeof ApiOrgSlugRequestsReplayRouteImport
      parentRoute: typeof ApiOrgSlugRequestsRoute
    }
    '/api/$orgSlug/requests/capture': {
      id: '/api/$orgSlug/requests/capture'
      path: '/capture'
      fullPath: '/api/$orgSlug/requests/capture'
      preLoaderRoute: typeof ApiOrgSlugRequestsCaptureRouteImport
      parentRoute: typeof ApiOrgSlugRequestsRoute
    }
    '/api/$orgSlug/portal/polar': {
      id: '/api/$orgSlug/portal/polar'
      path: '/api/$orgSlug/portal/polar'
      fullPath: '/api/$orgSlug/portal/polar'
      preLoaderRoute: typeof ApiOrgSlugPortalPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/domains/$domainId': {
      id: '/api/$orgSlug/domains/$domainId'
      path: '/api/$orgSlug/domains/$domainId'
      fullPath: '/api/$orgSlug/domains/$domainId'
      preLoaderRoute: typeof ApiOrgSlugDomainsDomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/tunnels/$tunnelId/stop': {
      id: '/api/$orgSlug/tunnels/$tunnelId/stop'
      path: '/stop'
      fullPath: '/api/$orgSlug/tunnels/$tunnelId/stop'
      preLoaderRoute: typeof ApiOrgSlugTunnelsTunnelIdStopRouteImport
      parentRoute: typeof ApiOrgSlugTunnelsTunnelIdRoute
    }
    '/api/$orgSlug/domains/$domainId/verify': {
      id: '/api/$orgSlug/domains/$domainId/verify'
      path: '/verify'
      fullPath: '/api/$orgSlug/domains/$domainId/verify'
      preLoaderRoute: typeof ApiOrgSlugDomainsDomainIdVerifyRouteImport
      parentRoute: typeof ApiOrgSlugDomainsDomainIdRoute
    }
  }
}

interface OrgSlugSettingsRouteChildren {
  OrgSlugSettingsOrganizationRoute: typeof OrgSlugSettingsOrganizationRoute
  OrgSlugSettingsProfileRoute: typeof OrgSlugSettingsProfileRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugSettingsRouteChildren: OrgSlugSettingsRouteChildren = {
  OrgSlugSettingsOrganizationRoute: OrgSlugSettingsOrganizationRoute,
  OrgSlugSettingsProfileRoute: OrgSlugSettingsProfileRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugSettingsRouteWithChildren = OrgSlugSettingsRoute._addFileChildren(
  OrgSlugSettingsRouteChildren,
)

interface OrgSlugRouteChildren {
  OrgSlugBillingRoute: typeof OrgSlugBillingRoute
  OrgSlugDomainsRoute: typeof OrgSlugDomainsRoute
  OrgSlugInstallRoute: typeof OrgSlugInstallRoute
  OrgSlugMembersRoute: typeof OrgSlugMembersRoute
  OrgSlugRequestsRoute: typeof OrgSlugRequestsRoute
  OrgSlugSettingsRoute: typeof OrgSlugSettingsRouteWithChildren
  OrgSlugSubdomainsRoute: typeof OrgSlugSubdomainsRoute
  OrgSlugTokensRoute: typeof OrgSlugTokensRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugTunnelsTunnelIdRoute: typeof OrgSlugTunnelsTunnelIdRoute
  OrgSlugTunnelsIndexRoute: typeof OrgSlugTunnelsIndexRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugBillingRoute: OrgSlugBillingRoute,
  OrgSlugDomainsRoute: OrgSlugDomainsRoute,
  OrgSlugInstallRoute: OrgSlugInstallRoute,
  OrgSlugMembersRoute: OrgSlugMembersRoute,
  OrgSlugRequestsRoute: OrgSlugRequestsRoute,
  OrgSlugSettingsRoute: OrgSlugSettingsRouteWithChildren,
  OrgSlugSubdomainsRoute: OrgSlugSubdomainsRoute,
  OrgSlugTokensRoute: OrgSlugTokensRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugTunnelsTunnelIdRoute: OrgSlugTunnelsTunnelIdRoute,
  OrgSlugTunnelsIndexRoute: OrgSlugTunnelsIndexRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

interface ApiOrgSlugRequestsRouteChildren {
  ApiOrgSlugRequestsCaptureRoute: typeof ApiOrgSlugRequestsCaptureRoute
  ApiOrgSlugRequestsReplayRoute: typeof ApiOrgSlugRequestsReplayRoute
}

const ApiOrgSlugRequestsRouteChildren: ApiOrgSlugRequestsRouteChildren = {
  ApiOrgSlugRequestsCaptureRoute: ApiOrgSlugRequestsCaptureRoute,
  ApiOrgSlugRequestsReplayRoute: ApiOrgSlugRequestsReplayRoute,
}

const ApiOrgSlugRequestsRouteWithChildren =
  ApiOrgSlugRequestsRoute._addFileChildren(ApiOrgSlugRequestsRouteChildren)

interface ApiCliLoginRouteChildren {
  ApiCliLoginStatusRoute: typeof ApiCliLoginStatusRoute
}

const ApiCliLoginRouteChildren: ApiCliLoginRouteChildren = {
  ApiCliLoginStatusRoute: ApiCliLoginStatusRoute,
}

const ApiCliLoginRouteWithChildren = ApiCliLoginRoute._addFileChildren(
  ApiCliLoginRouteChildren,
)

interface ApiOrgSlugDomainsDomainIdRouteChildren {
  ApiOrgSlugDomainsDomainIdVerifyRoute: typeof ApiOrgSlugDomainsDomainIdVerifyRoute
}

const ApiOrgSlugDomainsDomainIdRouteChildren: ApiOrgSlugDomainsDomainIdRouteChildren =
  {
    ApiOrgSlugDomainsDomainIdVerifyRoute: ApiOrgSlugDomainsDomainIdVerifyRoute,
  }

const ApiOrgSlugDomainsDomainIdRouteWithChildren =
  ApiOrgSlugDomainsDomainIdRoute._addFileChildren(
    ApiOrgSlugDomainsDomainIdRouteChildren,
  )

interface ApiOrgSlugTunnelsTunnelIdRouteChildren {
  ApiOrgSlugTunnelsTunnelIdStopRoute: typeof ApiOrgSlugTunnelsTunnelIdStopRoute
}

const ApiOrgSlugTunnelsTunnelIdRouteChildren: ApiOrgSlugTunnelsTunnelIdRouteChildren =
  {
    ApiOrgSlugTunnelsTunnelIdStopRoute: ApiOrgSlugTunnelsTunnelIdStopRoute,
  }

const ApiOrgSlugTunnelsTunnelIdRouteWithChildren =
  ApiOrgSlugTunnelsTunnelIdRoute._addFileChildren(
    ApiOrgSlugTunnelsTunnelIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  AdminRoute: AdminRoute,
  EmailTemplatesRoute: EmailTemplatesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SelectRoute: SelectRoute,
  SignupRoute: SignupRoute,
  ApiSearchRoute: ApiSearchRoute,
  CliLoginRoute: CliLoginRoute,
  DocsSplatRoute: DocsSplatRoute,
  InternalDomainCheckRoute: InternalDomainCheckRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  ApiOrgSlugAuthTokensRoute: ApiOrgSlugAuthTokensRoute,
  ApiOrgSlugRequestsRoute: ApiOrgSlugRequestsRouteWithChildren,
  ApiOrgSlugSettingsRoute: ApiOrgSlugSettingsRoute,
  ApiOrgSlugSubscriptionsRoute: ApiOrgSlugSubscriptionsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckoutPolarRoute: ApiCheckoutPolarRoute,
  ApiCliCompleteRoute: ApiCliCompleteRoute,
  ApiCliExchangeRoute: ApiCliExchangeRoute,
  ApiCliLoginRoute: ApiCliLoginRouteWithChildren,
  ApiDomainVerifyOwnershipRoute: ApiDomainVerifyOwnershipRoute,
  ApiMeOrgsRoute: ApiMeOrgsRoute,
  ApiOrganizationsCheckSlugRoute: ApiOrganizationsCheckSlugRoute,
  ApiSubscriptionsOrganizationIdRoute: ApiSubscriptionsOrganizationIdRoute,
  ApiTunnelAuthRoute: ApiTunnelAuthRoute,
  ApiTunnelCheckSubdomainRoute: ApiTunnelCheckSubdomainRoute,
  ApiTunnelRegisterRoute: ApiTunnelRegisterRoute,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
  ApiOrgSlugDomainsDomainIdRoute: ApiOrgSlugDomainsDomainIdRouteWithChildren,
  ApiOrgSlugPortalPolarRoute: ApiOrgSlugPortalPolarRoute,
  ApiOrgSlugStatsBandwidthRoute: ApiOrgSlugStatsBandwidthRoute,
  ApiOrgSlugStatsOverviewRoute: ApiOrgSlugStatsOverviewRoute,
  ApiOrgSlugStatsProtocolRoute: ApiOrgSlugStatsProtocolRoute,
  ApiOrgSlugStatsTunnelRoute: ApiOrgSlugStatsTunnelRoute,
  ApiOrgSlugSubdomainsSubdomainIdRoute: ApiOrgSlugSubdomainsSubdomainIdRoute,
  ApiOrgSlugTunnelsTunnelIdRoute: ApiOrgSlugTunnelsTunnelIdRouteWithChildren,
  ApiOrgSlugDomainsIndexRoute: ApiOrgSlugDomainsIndexRoute,
  ApiOrgSlugSubdomainsIndexRoute: ApiOrgSlugSubdomainsIndexRoute,
  ApiOrgSlugTunnelsIndexRoute: ApiOrgSlugTunnelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
